### ISSUE TITLE
COCO panoptic_val2017.json upload error

### ISSUE THREAD

**Issue by fanrupin** [openvinotoolkit/cvat#1143]
When i upload annotations of COCO JSON 1.0, i choose local [panoptic_val2017.json,](http://cocodataset.org/index.htm#download) then it reports error as follow:

> Could not upload annotation for the task 2
Error: Request failed with status code 500. "cvat.apps.engine.utils.InterpreterError: KeyError at line 98: id\n".

log:

> 2020-02-15 09:53:13,234 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.234025 2020] [wsgi:error] [pid 247:tid 140270339311360] [remote 10.130.150.248:6925] [2020-02-15 09:53:13,233] INFO revproxy.view: ProxyView created
2020-02-15 09:53:13,245 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.245463 2020] [wsgi:error] [pid 247:tid 140270339311360] [remote 10.130.150.248:6925] [2020-02-15 09:53:13,245] INFO revproxy.view: REMOTE_USER set
2020-02-15 09:53:13,247 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.247124 2020] [wsgi:error] [pid 247:tid 140270339311360] [remote 10.130.150.248:6925] [2020-02-15 09:53:13,247] DEBUG revproxy.view: Dispatch full path: /analytics/app/kibana
2020-02-15 09:53:13,248 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.248646 2020] [wsgi:error] [pid 247:tid 140270339311360] [remote 10.130.150.248:6925] [2020-02-15 09:53:13,248] DEBUG revproxy.view: Request headers: {'Accept': 'application/json, text/plain, */*', 'Accept-Language': 'en-US,en;q=0.9', 'REMOTE_USER': 'admin', 'X-Forwarded-User': 'admin', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36', 'X-Csrftoken': 'oSXaAyydNe2BvvCCRCcma4dU41vxhaNQPkxQSTgGYrKlagZInJvjbZswlbm9WuXd', 'Authorization': 'Token fb827a29cb237706f48523291328193993cacba9', 'Origin': 'http://10.107.201.242:7080', 'Cookie': 'sessionid=b66cyjdou6xticlgril0ucxvhfkth994; csrftoken=oSXaAyydNe2BvvCCRCcma4dU41vxhaNQPkxQSTgGYrKlagZInJvjbZswlbm9WuXd', 'Referer': 'http://10.107.201.242:7080/tasks/5', 'Connection': 'keep-alive'}
2020-02-15 09:53:13,250 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.250306 2020] [wsgi:error] [pid 247:tid 140270339311360] [remote 10.130.150.248:6925] [2020-02-15 09:53:13,250] DEBUG revproxy.view: Request URL: http://kibana:5601/app/kibana
2020-02-15 09:53:13,262 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.262320 2020] [wsgi:error] [pid 247:tid 140270339311360] [remote 10.130.150.248:6925] [2020-02-15 09:53:13,262] DEBUG revproxy.view: Proxy response header: HTTPHeaderDict({'kbn-name': 'kibana', 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-cache', 'Date': 'Sat, 15 Feb 2020 09:53:13 GMT', 'accept-ranges': 'bytes', 'content-length': '58838', 'vary': 'accept-encoding', 'Connection': 'keep-alive'})
2020-02-15 09:53:13,262 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.262626 2020] [wsgi:error] [pid 247:tid 140270339311360] [remote 10.130.150.248:6925] [2020-02-15 09:53:13,262] DEBUG revproxy.response: Proxy response headers: HTTPHeaderDict({'kbn-name': 'kibana', 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-cache', 'Date': 'Sat, 15 Feb 2020 09:53:13 GMT', 'accept-ranges': 'bytes', 'content-length': '58838', 'vary': 'accept-encoding', 'Connection': 'keep-alive'})
2020-02-15 09:53:13,263 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.262879 2020] [wsgi:error] [pid 247:tid 140270339311360] [remote 10.130.150.248:6925] [2020-02-15 09:53:13,262] DEBUG revproxy.response: Content-Type: text/html; charset=utf-8
2020-02-15 09:53:13,263 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.263217 2020] [wsgi:error] [pid 247:tid 140270339311360] [remote 10.130.150.248:6925] [2020-02-15 09:53:13,263] INFO revproxy.response: Normalizing response headers
2020-02-15 09:53:13,263 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.263505 2020] [wsgi:error] [pid 247:tid 140270339311360] [remote 10.130.150.248:6925] [2020-02-15 09:53:13,263] DEBUG revproxy.cookies: Response headers: {'kbn-name': ('Kbn-Name', 'kibana'), 'content-type': ('Content-Type', 'text/html; charset=utf-8'), 'cache-control': ('Cache-Control', 'no-cache'), 'date': ('Date', 'Sat, 15 Feb 2020 09:53:13 GMT'), 'accept-ranges': ('Accept-Ranges', 'bytes'), 'content-length': ('Content-Length', '58838'), 'vary': ('Vary', 'accept-encoding')}
2020-02-15 09:53:13,263 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.263681 2020] [wsgi:error] [pid 247:tid 140270339311360] [remote 10.130.150.248:6925] [2020-02-15 09:53:13,263] DEBUG revproxy.response: Response headers: {'kbn-name': ('Kbn-Name', 'kibana'), 'content-type': ('Content-Type', 'text/html; charset=utf-8'), 'cache-control': ('Cache-Control', 'no-cache'), 'date': ('Date', 'Sat, 15 Feb 2020 09:53:13 GMT'), 'accept-ranges': ('Accept-Ranges', 'bytes'), 'content-length': ('Content-Length', '58838'), 'vary': ('Vary', 'accept-encoding')}
2020-02-15 09:53:13,263 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.263854 2020] [wsgi:error] [pid 247:tid 140270339311360] [remote 10.130.150.248:6925] [2020-02-15 09:53:13,263] INFO revproxy.response: Checking for invalid cookies
2020-02-15 09:53:13,264 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.264014 2020] [wsgi:error] [pid 247:tid 140270339311360] [remote 10.130.150.248:6925] [2020-02-15 09:53:13,263] DEBUG revproxy.response: Response cookies:
2020-02-15 09:53:13,264 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.264177 2020] [wsgi:error] [pid 247:tid 140270339311360] [remote 10.130.150.248:6925] [2020-02-15 09:53:13,264] DEBUG revproxy.view: RESPONSE RETURNED: <HttpResponse status_code=200, "text/html; charset=utf-8">
2020-02-15 09:53:13,674 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:13.673679 2020] [wsgi:error] [pid 247:tid 140270330918656] [remote 10.130.150.248:6935] [2020-02-15 09:53:13,673] INFO cvat.server.task_5: get repository request
2020-02-15 09:53:29,699 DEBG 'rqworker_default_0' stderr output:
09:53:29 default: cvat.apps.engine.annotation.load_task_data('2', <User: admin>, '/tmp/cvat_2mgaxikp7', <AnnotationLoader: AnnotationLoader object (COCO JSON 1.0)>) (admin@/api/v1/tasks/2/annotations/upload)
2020-02-15 09:53:31,498 DEBG 'rqworker_default_0' stderr output:
09:53:31 cvat.apps.engine.utils.InterpreterError: KeyError at line 98: id
Traceback (most recent call last):
  File "/home/django/cvat/apps/engine/utils.py", line 45, in execute_python_code
    exec(source_code, global_vars, local_vars)
  File "<string>", line 1, in <module>
  File "<string>", line 340, in load
  File "/usr/local/lib/python3.5/dist-packages/pycocotools/coco.py", line 88, in __init__
    self.createIndex()
  File "/usr/local/lib/python3.5/dist-packages/pycocotools/coco.py", line 98, in createIndex
    anns[ann['id']] = ann
KeyError: 'id'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/annotation.py", line 112, in load_task_data
    annotation.upload(filename, loader)
  File "/home/django/cvat/apps/engine/annotation.py", line 760, in upload
    execute_python_code("{}(file_object, annotations)".format(loader.handler), global_vars)
  File "/home/django/cvat/apps/engine/utils.py", line 60, in execute_python_code
    raise InterpreterError("{} at line {}: {}".format(error_class, line_number, details))
cvat.apps.engine.utils.InterpreterError: KeyError at line 98: id
Traceback (most recent call last):
  File "/home/django/cvat/apps/engine/utils.py", line 45, in execute_python_code
    exec(source_code, global_vars, local_vars)
  File "<string>", line 1, in <module>
  File "<string>", line 340, in load
  File "/usr/local/lib/python3.5/dist-packages/pycocotools/coco.py", line 88, in __init__
    self.createIndex()
  File "/usr/local/lib/python3.5/dist-packages/pycocotools/coco.py", line 98, in createIndex
    anns[ann['id']] = ann
KeyError: 'id'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/annotation.py", line 112, in load_task_data
    annotation.upload(filename, loader)
  File "/home/django/cvat/apps/engine/annotation.py", line 760, in upload
    execute_python_code("{}(file_object, annotations)".format(loader.handler), global_vars)
  File "/home/django/cvat/apps/engine/utils.py", line 60, in execute_python_code
    raise InterpreterError("{} at line {}: {}".format(error_class, line_number, details))
cvat.apps.engine.utils.InterpreterError: KeyError at line 98: id
2020-02-15 09:53:31,626 DEBG 'rqworker_default_0' stderr output:
09:53:31 Cleaning registries for queue: default
2020-02-15 09:53:32,747 DEBG 'runserver' stderr output:
[Sat Feb 15 09:53:32.747455 2020] [wsgi:error] [pid 247:tid 140270330918656] [remote 10.130.150.248:6950] [2020-02-15 09:53:32,747] ERROR django.request: Internal Server Error: /api/v1/tasks/2/annotations

**Comment by azhavoro** [comment]
@fanrupin Hi, thanks for the report, need some time to investigate.

**Comment by zhiltsov-max** [comment]
COCO panoptic task is not supported yet.

**Comment by zhiltsov-max** [comment]
Should already be resolved.
