### ISSUE TITLE
can't create tasks: Combined data types are not supported.

### ISSUE THREAD

**Issue by jayagami** [openvinotoolkit/cvat#2211]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

An error occurred when creating a task: 

`Error: Could not create the task on the server. Exception: Combined data types are not supported.`

images upload from `Connected file share`.

### Expected Behaviour

create tasks successfully.

### Current Behaviour

Could not create the task
Error: Could not create the task on the server. Exception: Combined data types are not supported.

### Possible Solution

create a small dataset, not import all images one time.

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

Docker version 19.03.13, build 4484c46d9d
Docker Swarm 
Ubuntu 20.04

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 883, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 645, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 651, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 239, in _create_thread
    raise Exception('Combined data types are not supported')
Exception: Combined data types are not supported
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 883, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 645, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 651, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 239, in _create_thread
    raise Exception('Combined data types are not supported')
Exception: Combined data types are not supported
```

### Next steps

You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by zhiltsov-max** [comment]
CVAT does not support different data types for a task. It can be resolved with projects soon, which will combine few tasks together.
