### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by magnusja** [openvinotoolkit/cvat#2316]
### Steps to Reproduce (for bugs)

1. Dump task annotations in CVAT image 1.1 format

### Your Environment
CVAT 1.1 (git tag), within docker compose
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 883, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 645, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 651, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 87, in export_task_annotations
    return export_task(task_id, dst_format, server_url=server_url, save_images=False)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 62, in export_task
    server_url=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 748, in export_task
    task.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 630, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 553, in _export_images
    anno_callback=dump_as_cvat_annotation, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 526, in _export
    anno_callback(f, task_data)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 239, in dump_as_cvat_annotation
    dumper.open_box(dump_data)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 93, in open_box
    self.xmlgen.startElement("box", box)
  File "/usr/lib/python3.5/xml/sax/saxutils.py", line 171, in startElement
    self._write(' %s=%s' % (name, quoteattr(value)))
  File "/usr/lib/python3.5/xml/sax/saxutils.py", line 61, in quoteattr
    data = escape(data, entities)
  File "/usr/lib/python3.5/xml/sax/saxutils.py", line 27, in escape
    data = data.replace("&", "&amp;")
AttributeError: 'NoneType' object has no attribute 'replace'

```

**Comment by nmanovic** [comment]
@magnusja , I believe the problem was solved. Could you please try again and confirm? I will close the issue as outdated.

**Comment by keshavadk** [comment]
I got the same error "AttributeError: 'NoneType' object has no attribute 'replace'\n" while exporting the 'task data dataset'.

The error image is attached below.
![Attribute error](https://user-images.githubusercontent.com/16021947/152687777-8f42a247-eb64-4007-aaf2-a338b8306117.JPG)

**Comment by zhiltsov-max** [comment]
@keshavadk, please add version info and CVAT container logs (`docker logs cvat`)
