### ISSUE TITLE
big zipfile ,create task,django-rq , django.db.utils.OperationalError: connection not open

### ISSUE THREAD

**Issue by JK-97** [openvinotoolkit/cvat#2353]
# env
- deploy on k8s
- production 
- commit : 5d40d6c8   

# question
### Upload a data set with a size of 4gb, when the compression reaches 100%. django-rq tasks will report errors
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/engine/task.py", line 312, in _create_thread
    models.Image.objects.bulk_create(db_images)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cacheops/query.py", line 380, in bulk_create
    objs = self._no_monkey.bulk_create(self, objs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 474, in bulk_create
    ids = self._batched_insert(objs_without_pk, fields, batch_size, ignore_conflicts=ignore_conflicts)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1204, in _batched_insert
    ignore_conflicts=ignore_conflicts,
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1375, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/cacheops/transaction.py", line 93, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: connection not open
```

# what i had do for this question

i have try close connection before orm create, then call connection.cursor will get a fresh connection, django source code:
```
def _cursor(self, name=None):
    self.ensure_connection()
    with self.wrap_database_errors:
        return self._prepare_cursor(self.create_cursor(name))
```
beside,  set  `CONN_MAX_AGE=36000` in settings.py

branch : 5d40d6c8   
file : cvat/apps/engine/task.py    _create_thread()

```
from django.db import connections, connection

    ......
    for conn in connections.all():       #add
        conn.close_if_unusable_or_obsolete()    #add
    if db_task.mode == 'annotation':
        models.Image.objects.bulk_create(db_images)
        db_images = []
    else:
        models.Video.objects.create(
            data=db_data,
            path=os.path.relpath(video_path, upload_dir),
            width=video_size[0], height=video_size[1])

```
### but 
what i had do cause another error :  django.db.utils.interfaceerror: connection already closed

### Please help me to solve this problem，thanks

**Comment by JK-97** [comment]
i have hot fix this bug ：
Solution is Shorten the use interval of the `bulk_create()` method to keep the connection live：like this


```
    for chunk_idx, chunk_data in generator:
        chunk_data = list(chunk_data)
        original_chunk_path = db_data.get_original_chunk_path(chunk_idx)
        original_chunk_writer.save_as_chunk(chunk_data, original_chunk_path)

        compressed_chunk_path = db_data.get_compressed_chunk_path(chunk_idx)
        img_sizes = compressed_chunk_writer.save_as_chunk(chunk_data, compressed_chunk_path)

        if db_task.mode == 'annotation':
           # keep the db connection live
            models.Image.objects.bulk_create([
                models.Image(
                    data=db_data,
                    path=os.path.relpath(data[1], upload_dir),
                    frame=data[2],
                    width=size[0],
                    height=size[1])

                for data, size in zip(chunk_data, img_sizes)
            ])
        else:
            video_size = img_sizes[0]
            video_path = chunk_data[0][1]

        db_data.size += len(chunk_data)
        progress = extractor.get_progress(chunk_data[-1][2])
        update_progress(progress)

    if db_task.mode == 'annotation':
        pass
    else:
        models.Video.objects.create(
            data=db_data,
            path=os.path.relpath(video_path, upload_dir),
            width=video_size[0], height=video_size[1])
```

**Comment by nmanovic** [comment]
@JK-97 , it is great that you solved the issue on your side. CVAT server was changed significantly. I will close the issue as outdated. Don't hesitate to reopen, if you still see the issue.

**Comment by chaoyifei** [comment]
> bulk_create
i have same errors in /api/v1/jobs/1/annotations, when bulk create annotations,
CONN_MAX_AGE=60 in settings.py
