### ISSUE TITLE
patool error: error extracting /tmp/cvat_4zsw0uh0e: unknown archive format for file `/tmp/cvat_4zsw0uh0e'

### ISSUE THREAD

**Issue by abhishekchopde** [openvinotoolkit/cvat#2396]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

### Expected Behaviour
Should be able to upload MOT1.1 format annotations for my dataset. I have a csv file  with the specified format.

### Current Behaviour

Out put of `docker logs cvat` shows the follwoing error:
```
ERROR:rq.worker:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 766, in import_job_annotations
    job.import_annotations(f, importer)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 555, in import_annotations
    importer(src_file, task_data)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/mot.py", line 30, in _import
    Archive(src_file.name).extractall(tmp_dir)
  File "/usr/local/lib/python3.8/dist-packages/pyunpack/__init__.py", line 94, in extractall
    self.extractall_patool(directory, patool_path)
  File "/usr/local/lib/python3.8/dist-packages/pyunpack/__init__.py", line 65, in extractall_patool
    raise PatoolError("patool can not unpack\n" + str(p.stderr))
pyunpack.PatoolError: patool can not unpack
patool error: error extracting /tmp/cvat_4zsw0uh0e: unknown archive format for file `/tmp/cvat_4zsw0uh0e'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.8/dist-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 766, in import_job_annotations
    job.import_annotations(f, importer)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 555, in import_annotations
    importer(src_file, task_data)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/mot.py", line 30, in _import
    Archive(src_file.name).extractall(tmp_dir)
  File "/usr/local/lib/python3.8/dist-packages/pyunpack/__init__.py", line 94, in extractall
    self.extractall_patool(directory, patool_path)
  File "/usr/local/lib/python3.8/dist-packages/pyunpack/__init__.py", line 65, in extractall_patool
    raise PatoolError("patool can not unpack\n" + str(p.stderr))
pyunpack.PatoolError: patool can not unpack
patool error: error extracting /tmp/cvat_4zsw0uh0e: unknown archive format for file `/tmp/cvat_4zsw0uh0e'
```

### Context
My annotation file looks like:
```
frame,id,bb_left,bb_top,bb_width,bb_height,conf,x,y,z
1,0,503,390,527,461,1,-1,-1,-1
1,0,478,68,497,125,1,-1,-1,-1
1,0,449,28,470,75,1,-1,-1,-1

```

**Comment by zhiltsov-max** [comment]
Hi, the expected file format is described here:  https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/dataset_manager/formats/README.md#mot-loader

**Comment by abhishekchopde** [comment]
@zhiltsov-max thanks for pointing out. Some how I was not able to find this documentaion.
