### ISSUE TITLE
TypeError: can only concatenate str (not "ssl.SSLError") to str.

### ISSUE THREAD

**Issue by HaziqRazali** [openvinotoolkit/cvat#2446]
Creating a new task with https://data.bris.ac.uk/datasets/3h91syskeag572hl6tvuovwv4d/videos/train/P01/P01_01.MP4 as the URL for remote source returns the error

```
Could not create the task
Error: Could not create the task on the server. TypeError: can only concatenate str (not "ssl.SSLError") to str.
```

**Comment by azhavoro** [comment]
Full stack:
```python
Traceback (most recent call last):
  File "/home/django/cvat/apps/engine/task.py", line 199, in _download_data
    with urlrequest.urlopen(req) as fp, open(os.path.join(upload_dir, name), 'wb') as tfp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1123)>
```

From https://wiki.debian.org/ContinuousIntegration/TriagingTips/openssl-1.1.1: "This is caused by the SECLEVEL 2 setting the security level to 112 bit. This means that RSA and DHE keys need to be at least 2048 bit long"  

So, I think it's not a good idea to reduce the SECLEVEL in `/etc/ssl/openssl.cnf` by default, but you try to do it for your installation.

If you still have questions, feel free to reopen the issue.
