### ISSUE TITLE
Cannot remove a project [TypeError: Cannot read property 'id' of undefined]

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#2625]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Can delete a project from the project page

### Current Behaviour
TypeError: Cannot read property 'id' of undefined
    at onClick (https://cvat.org/cvat-ui.01c9b98dbeebe6bcac43.min.js:365:546630)
    at onClick (https://cvat.org/cvat-ui.01c9b98dbeebe6bcac43.min.js:24:197793)
    at e.onClick (https://cvat.org/cvat-ui.01c9b98dbeebe6bcac43.min.js:24:205970)
    at Object.s (https://cvat.org/cvat-ui.01c9b98dbeebe6bcac43.min.js:341:457)
    at f (https://cvat.org/cvat-ui.01c9b98dbeebe6bcac43.min.js:341:600)
    at https://cvat.org/cvat-ui.01c9b98dbeebe6bcac43.min.js:341:746
    at b (https://cvat.org/cvat-ui.01c9b98dbeebe6bcac43.min.js:341:832)
    at it (https://cvat.org/cvat-ui.01c9b98dbeebe6bcac43.min.js:341:16360)
    at rt (https://cvat.org/cvat-ui.01c9b98dbeebe6bcac43.min.js:341:16170)
    at st (https://cvat.org/cvat-ui.01c9b98dbeebe6bcac43.min.js:341:16526)

### Possible Solution
Fix the bug

### Steps to Reproduce (for bugs)

1. Go to project page
1. Try to delete the project via actions

### Context
Functional doesn't work

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
@dvkruchinin Could you please write a test after the fix?
