### ISSUE TITLE
Nuclio related 500 server error

### ISSUE THREAD

**Issue by yaochenglouis** [openvinotoolkit/cvat#2641]
### My actions before raising this issue
- [ yes ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ yes ] Searched [past issues](/issues)

### Current Behaviour
I have so far deployed Dextr and GPU tf faster rcnn on cvat. i used them right after deployment and they went well. but after a reboot of system they wont work anymore. saying :
`Interaction error occured
Error: Request failed with status code 500. "500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations".`

I have been deleting functions in nuctl and re deploying them, which gives me the same 500 error. Tho my nuctl version is 1.5.10, which is not the same with the official one. 

and i also encountered this issue [https://github.com/nuclio/nuclio/issues/2027#issue-776533528](url)

I believe a thorough reinstall of both docker and cvat might solve the problem before my computer restarts after that...

### Your Environment

- cvat version 1.2.0
- Docker version    20.10.1
- Operating System and version : ubuntu 1804
- nuctl version : 1.5.10 
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.
docker logs cvat : 

```

2021-01-04 07:37:31,381 DEBG 'runserver' stderr output:
[Mon Jan 04 07:37:31.380811 2021] [wsgi:error] [pid 712:tid 140249678059264] [remote 172.28.0.4:57076] INFO:cvat.client:{"client_id":845691,"name":"Send user activity","time":"2021-01-04T07:37:32.110000Z","payload":{"working_time":6417},"is_active":true,"username":""}

2021-01-04 07:37:41,729 DEBG 'rqworker_default_1' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2021-01-04 07:37:41,730 DEBG 'rqworker_low' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.
INFO:rq.worker:Cleaning registries for queue: low

2021-01-04 07:37:41,971 DEBG 'rqworker_default_0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2021-01-04 07:38:09,026 DEBG 'runserver' stderr output:
[Mon Jan 04 07:38:09.025994 2021] [wsgi:error] [pid 712:tid 140249661273856] [remote 172.28.0.4:57110] [2021-01-04 07:38:09,025] ERROR django.request: Internal Server Error: /api/v1/lambda/functions/openvino-dextr

2021-01-04 07:38:09,026 DEBG 'runserver' stderr output:
[Mon Jan 04 07:38:09.026431 2021] [wsgi:error] [pid 712:tid 140249661273856] [remote 172.28.0.4:57110] ERROR:django.request:Internal Server Error: /api/v1/lambda/functions/openvino-dextr

2021-01-04 07:39:40,750 DEBG 'runserver' stderr output:
[Mon Jan 04 07:39:40.750004 2021] [wsgi:error] [pid 712:tid 140249686451968] [remote 172.28.0.4:57270] [2021-01-04 07:39:40,749] ERROR django.request: Internal Server Error: /api/v1/lambda/functions/openvino-dextr

2021-01-04 07:39:40,751 DEBG 'runserver' stderr output:
[Mon Jan 04 07:39:40.750389 2021] [wsgi:error] [pid 712:tid 140249686451968] [remote 172.28.0.4:57270] ERROR:django.request:Internal Server Error: /api/v1/lambda/functions/openvino-dextr
```

selected from 'docker logs nuclio' 

```
21.01.04 07:43:13.420 ashboard.platform.invoker (I) Executing function {"method": "POST", "url": "http://172.17.0.1:49155", "headers": {"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Connection":["close"],"Content-Length":["1405352"],"Content-Type":["application/json"],"User-Agent":["python-requests/2.24.0"],"X-Nuclio-Function-Name":["openvino-dextr"],"X-Nuclio-Function-Namespace":["nuclio"],"X-Nuclio-Log-Level":[""],"X-Nuclio-Path":["/"],"X-Nuclio-Project-Name":["cvat"],"X-Nuclio-Target":["openvino-dextr"]}}

21.01.04 07:46:53.672 dashboard.platform.docker (D) Container is healthy {"containerID": "3bb4b0d99fca17ab3564c536aba272b4469601d7d9626f3b34346a87865314ae"}
21.01.04 07:46:56.519 .api/function_invocations (W) Failed to invoke function {"err": "Failed to send HTTP request", "errVerbose": "\nError - Post \"http://172.17.0.1:49155\": dial tcp 172.17.0.1:49155: i/o timeout\n    /nuclio/pkg/platform/abstract/invoker.go:119\n\nCall stack:\nFailed to send HTTP request\n    /nuclio/pkg/platform/abstract/invoker.go:119\nFailed to send HTTP request", "errCauses": [{"error": "Post \"http://172.17.0.1:49155\": dial tcp 172.17.0.1:49155: i/o timeout"}]}
21.01.04 07:46:56.519          dashboard.server (D) Handled request {"requestMethod": "POST", "requestPath": "/api/function_invocations", "requestHeaders": {"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Connection":["close"],"Content-Length":["1405384"],"Content-Type":["application/json"],"User-Agent":["python-requests/2.24.0"],"X-Nuclio-Function-Name":["openvino-dextr"],"X-Nuclio-Function-Namespace":["nuclio"],"X-Nuclio-Log-Level":[""],"X-Nuclio-Path":["/"],"X-Nuclio-Project-Name":["cvat"],"X-Nuclio-Target":["openvino-dextr"]}, "requestBody": "{\"image\": \"iV"
, \"points\": [[500.02734375, 315.7109375], [479.892578125, 347.9267578125], [570.900390625, 408.330078125], [516.134765625, 426.8544921875], [418.6826171875, 375.3095703125], [654.6611328125, 322.9599609375], [544.3232421875, 374.50390625]]}", "responseStatus": 500, "responseBody": "{\"error\": \"Failed to invoke function\"}", "responseTime": "30.147497479s"}
```

'docker logs nuclio-nuclio-openvino-dextr'

```
21.01.04 07:36:23.918 cessor.healthcheck.server (I) Listening {"listenAddress": ":8082"}
21.01.04 07:36:23.918            processor.http (D) Creating worker pool {"num": 2}
21.01.04 07:36:23.919 sor.http.w1.python.logger (D) Creating listener socket {"path": "/tmp/nuclio-rpc-bvpcatqr7t3i9donl7ug.sock"}
21.01.04 07:36:23.919 sor.http.w0.python.logger (D) Creating listener socket {"path": "/tmp/nuclio-rpc-bvpcatqr7t3i9donl7v0.sock"}
21.01.04 07:36:23.919 sor.http.w1.python.logger (D) Using Python wrapper script path {"path": "/opt/nuclio/_nuclio_wrapper.py"}
21.01.04 07:36:23.919 sor.http.w1.python.logger (D) Using Python handler {"handler": "main:handler"}
21.01.04 07:36:23.919 sor.http.w0.python.logger (D) Using Python wrapper script path {"path": "/opt/nuclio/_nuclio_wrapper.py"}
21.01.04 07:36:23.919 sor.http.w1.python.logger (D) Using Python executable {"path": "/opt/nuclio/common/python3"}
21.01.04 07:36:23.919 sor.http.w0.python.logger (D) Using Python handler {"handler": "main:handler"}
21.01.04 07:36:23.919 sor.http.w1.python.logger (D) Setting PYTHONPATH {"value": "PYTHONPATH=/opt/nuclio"}
21.01.04 07:36:23.919 sor.http.w0.python.logger (D) Using Python executable {"path": "/opt/nuclio/common/python3"}
21.01.04 07:36:23.919 sor.http.w1.python.logger (D) Running wrapper {"command": "/opt/nuclio/common/python3 -u /opt/nuclio/_nuclio_wrapper.py --handler main:handler --socket-path /tmp/nuclio-rpc-bvpcatqr7t3i9donl7ug.sock --platform-kind local --namespace nuclio --worker-id 1 --trigger-kind http --trigger-name myHttpTrigger"}
21.01.04 07:36:23.919 sor.http.w0.python.logger (D) Setting PYTHONPATH {"value": "PYTHONPATH=/opt/nuclio"}
21.01.04 07:36:23.919 sor.http.w0.python.logger (D) Running wrapper {"command": "/opt/nuclio/common/python3 -u /opt/nuclio/_nuclio_wrapper.py --handler main:handler --socket-path /tmp/nuclio-rpc-bvpcatqr7t3i9donl7v0.sock --platform-kind local --namespace nuclio --worker-id 0 --trigger-kind http --trigger-name myHttpTrigger"}
[setupvars.sh] OpenVINO environment initialized
[setupvars.sh] OpenVINO environment initialized
21.01.04 07:36:24.257 sor.http.w0.python.logger (I) Wrapper connected {"wid": 0, "pid": 24}
21.01.04 07:36:24.257 sor.http.w0.python.logger (D) Waiting for start
l{"datetime": "2021-01-04 07:36:24,257", "level": "info", "message": "Init context...  0%", "with": {"worker_id": "0"}}
21.01.04 07:36:24.275 sor.http.w1.python.logger (I) Wrapper connected {"wid": 1, "pid": 23}
21.01.04 07:36:24.275 sor.http.w1.python.logger (D) Waiting for start
l{"datetime": "2021-01-04 07:36:24,275", "level": "info", "message": "Init context...  0%", "with": {"worker_id": "1"}}
l{"datetime": "2021-01-04 07:36:26,666", "level": "info", "message": "Init context...100%", "with": {"worker_id": "0"}}
l{"datetime": "2021-01-04 07:36:26,666", "level": "info", "message": "Replacing logger output", "with": {"handler_name": "default", "worker_id": "0"}}
21.01.04 07:36:26.666 sor.http.w0.python.logger (D) Started
l{"datetime": "2021-01-04 07:36:26,673", "level": "info", "message": "Init context...100%", "with": {"worker_id": "1"}}
l{"datetime": "2021-01-04 07:36:26,673", "level": "info", "message": "Replacing logger output", "with": {"handler_name": "default", "worker_id": "1"}}
21.01.04 07:36:26.674 sor.http.w1.python.logger (D) Started
21.01.04 07:36:26.674                 processor (I) Starting event timeout watcher {"timeout": "30s"}
21.01.04 07:36:26.674 .webadmin.server.triggers (D) Registered custom route {"pattern": "/{id}/stats", "method": "GET"}
21.01.04 07:36:26.674 processor.webadmin.server (D) Registered resource {"name": "triggers"}
21.01.04 07:36:26.674                 processor (W) No metric sinks configured, metrics will not be published
21.01.04 07:36:26.674                 processor (D) Starting triggers {"triggers": [{"ID":"myHttpTrigger","Logger":{},"WorkerAllocator":{},"Class":"sync","Kind":"http","Name":"myHttpTrigger","Statistics":{"EventsHandledSuccessTotal":0,"EventsHandledFailureTotal":0,"WorkerAllocatorStatistics":{"WorkerAllocationCount":0,"WorkerAllocationSuccessImmediateTotal":0,"WorkerAllocationSuccessAfterWaitTotal":0,"WorkerAllocationTimeoutTotal":0,"WorkerAllocationWaitDurationMilliSecondsSum":0,"WorkerAllocationWorkersAvailablePercentage":0}},"Namespace":"nuclio","FunctionName":"openvino-dextr"}]}
21.01.04 07:36:26.674            processor.http (I) Starting {"listenAddress": ":8080", "readBufferSize": 16384, "maxRequestBodySize": 33554432, "cors": null}
21.01.04 07:36:26.674 processor.webadmin.server (I) Listening {"listenAddress": ":8081"}
21.01.04 07:36:26.674                 processor (D) Processor started

```

'docker logs cvat_proxy'

```
10.162.187.190 - - [04/Jan/2021:07:37:32 +0000] "GET /api/v1/jobs/2/reviews HTTP/1.1" 200 2 "http://:38383/tasks/2/jobs/2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
10.162.187.190 - - [04/Jan/2021:07:38:09 +0000] "POST /api/v1/lambda/functions/openvino-dextr HTTP/1.1" 500 94 "http://38383/tasks/2/jobs/2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
10.162.187.190 - - [04/Jan/2021:07:39:40 +0000] "POST /api/v1/lambda/functions/openvino-dextr HTTP/1.1" 500 94 "http:///tasks/2/jobs/2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
10.162.187.190 - - [04/Jan/2021:07:43:43 +0000] "POST /api/v1/lambda/functions/openvino-dextr HTTP/1.1" 500 94 "h/tasks/2/jobs/2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
10.162.187.190 - - [04/Jan/2021:07:46:56 +0000] "POST /api/v1/lambda/functions/openvino-dextr HTTP/1.1" 500 94 "http://jobs/2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"

```
and in nuclio dashboard, when i test openvino-dextr, it says as well Status: 500 Internal Server Error with 
{
    "error": "Failed to invoke function"
}
so i tried invoking openvino-dextr in terminal. 
```
cvat@:~/cvat/serverless$ nuctl invoke openvino-dextr
21.01.04 16:25:39.773    nuctl.platform.invoker (I) Executing function {"method": "GET", "url": "http://:49155", "headers": {"Content-Type":["text/plain"],"X-Nuclio-Log-Level":["info"],"X-Nuclio-Target":["openvino-dextr"]}}
21.01.04 16:25:39.779    nuctl.platform.invoker (I) Got response {"status": "500 Internal Server Error"}
21.01.04 16:25:39.779                     nuctl (I) >>> Start of function logs
21.01.04 16:25:39.779            openvino-dextr (I) call handler {"time": 1609748739778.5774, "worker_id": "0"}
21.01.04 16:25:39.779            openvino-dextr (E) Exception caught in handler {"exc": "'NoneType' object is not subscriptable", "traceback": "Traceback (most recent call last):\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 114, in serve_requests\n    self._handle_event(event)\n  File \"/opt/nuclio/_nuclio_wrapper.py\", line 262, in _handle_event\n    entrypoint_output = self._entrypoint(self._context, event)\n  File \"/opt/nuclio/main.py\", line 18, in handler\n    points = data[\"points\"]\nTypeError: 'NoneType' object is not subscriptable\n", "worker_id": "0", "time": 1609748739779.3408}
21.01.04 16:25:39.779                     nuctl (I) <<< End of function logs

> Response headers:
Server = nuclio
Date = Mon, 04 Jan 2021 08:25:39 GMT
Content-Type = text/plain
Content-Length = 465

> Response body:
Exception caught in handler - "'NoneType' object is not subscriptable": Traceback (most recent call last):
  File "/opt/nuclio/_nuclio_wrapper.py", line 114, in serve_requests
    self._handle_event(event)
  File "/opt/nuclio/_nuclio_wrapper.py", line 262, in _handle_event
    entrypoint_output = self._entrypoint(self._context, event)
  File "/opt/nuclio/main.py", line 18, in handler
    points = data["points"]
TypeError: 'NoneType' object is not subscriptable

```

**Comment by yaochenglouis** [comment]
Very well, I have deleted docker storage path (/var/lib/docker) and reinstalled cvat, this error still exists.

**Comment by jahaniam** [comment]
You are invoking the function wrong. 

You need to pass data otherwise it is None. 
```
image=$(curl https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png --output - | base64 | tr -d '\n')
cat << EOF > /tmp/input.json
{"image": "$image"}
EOF
cat /tmp/input.json | nuctl invoke openvino.omz.public.yolo-v3-tf -c 'application/json'
```

**Comment by yaochenglouis** [comment]
> @yaochen You are invoking the function wrong.
> 
> You need to pass data otherwise it is None.
> 
> ```
> image=$(curl https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png --output - | base64 | tr -d '\n')
> cat << EOF > /tmp/input.json
> {"image": "$image"}
> EOF
> cat /tmp/input.json | nuctl invoke openvino.omz.public.yolo-v3-tf -c 'application/json'
> ```
> 
> Don't forget to change openvino.omz.public.yolo-v3-tf to your function name. This is for detector types. For dxtr you probably need to pass point values and image I am assuming.
> 
> > Very well, I have deleted docker storage path (/var/lib/docker) and reinstalled cvat, this error still exists.

thanks for your comment, but this was not the problem i wanted to solve. 
```
`cvat@:~/cvat/serverless$ nuctl invoke openvino-dextr
21.01.04 16:25:39.773    nuctl.platform.invoker (I) Executing function {"method": "GET", "url": "http://:49155", "headers": {"Content-Type":["text/plain"],"X-Nuclio-Log-Level":["info"],"X-Nuclio-Target":["openvino-dextr"]}}
21.01.04 16:25:39.779    nuctl.platform.invoker (I) Got response {"status": "500 Internal Server Error"}`
```
I encountered the 500 server error in this interface. I just want to make my Dextr work.
After click on four points on a photo, the coordinates and the task number, the order of photo will be sent as json by 'POST' method to somewhere I don't know, after a 30 seconds wait, it will say 500 error. 
![cv4at-dextr](https://user-images.githubusercontent.com/12840061/103786835-db916000-5077-11eb-94e6-44000f237c7d.png)
![500error](https://user-images.githubusercontent.com/12840061/103787426-86a21980-5078-11eb-8d12-e5a78122bc1a.png)

**Comment by yaochen** [comment]
wrong yao :)

**Comment by yaochenglouis** [comment]
> @yaochen You are invoking the function wrong.
> 
> You need to pass data otherwise it is None.
> 
> ```
> image=$(curl https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png --output - | base64 | tr -d '\n')
> cat << EOF > /tmp/input.json
> {"image": "$image"}
> EOF
> cat /tmp/input.json | nuctl invoke openvino.omz.public.yolo-v3-tf -c 'application/json'
> ```
> 
> Don't forget to change openvino.omz.public.yolo-v3-tf to your function name. This is for detector types. For dxtr you probably need to pass point values and image I am assuming.
> 
> > Very well, I have deleted docker storage path (/var/lib/docker) and reinstalled cvat, this error still exists.

ok i just tried the code you provided. with invoke function, faster rcnn inception v2 coco worked in terminal as below, but not with cvat web interface, still 500 error
```
cvat@server301:~/cvat-develop/serverless$ cat /tmp/input.json | nuctl invoke openvino-omz-public-faster_rcnn_inception_v2_coco -c 'application/json'
21.01.06 23:45:40.208    nuctl.platform.invoker (I) Executing function {"method": "POST", "url": "http://:49156", "headers": {"Content-Type":["application/json"],"X-Nuclio-Log-Level":["info"],"X-Nuclio-Target":["openvino-omz-public-faster_rcnn_inception_v2_coco"]}}
21.01.06 23:45:40.468    nuctl.platform.invoker (I) Got response {"status": "200 OK"}
21.01.06 23:45:40.468                     nuctl (I) >>> Start of function logs
21.01.06 23:45:40.468 er_rcnn_inception_v2_coco (I) Run faster_rcnn_inception_v2_coco model {"time": 1609947940213.0337, "worker_id": "0"}
21.01.06 23:45:40.468                     nuctl (I) <<< End of function logs

> Response headers:
Content-Type = application/json
Content-Length = 790
Server = nuclio
Date = Wed, 06 Jan 2021 15:45:40 GMT

> Response body:
[
    {
        "confidence": "0.8943716",
        "label": "person",
        "points": [
            43.75230407714844,
            88.84153747558594,
            468.51214599609375,
            503.792724609375
        ],
        "type": "rectangle"
    },
    {
        "confidence": "0.77300113",
        "label": "person",
        "points": [
            131.3173828125,
            133.52066040039062,
            408.25921630859375,
            504.3330993652344
        ],
        "type": "rectangle"
    },
    {
        "confidence": "0.7444026",
        "label": "person",
        "points": [
            389.31353759765625,
            260.0534973144531,
            511.5247802734375,
            510.0107727050781
        ],
        "type": "rectangle"
    },
    {
        "confidence": "0.5019484",
        "label": "person",
        "points": [
            356.7888488769531,
            174.8267059326172,
            505.1935119628906,
            500.98492431640625
        ],
        "type": "rectangle"
    },
    {
        "confidence": "0.9003211",
        "label": "umbrella",
        "points": [
            82.82101440429688,
            45.43473815917969,
            496.8105773925781,
            442.89654541015625
        ],
        "type": "rectangle"
    }
]

```

**Comment by yaochenglouis** [comment]
> wrong yao :)

lmao hey fellow yao, sorry for the inconvenience

**Comment by yaochenglouis** [comment]
![Screenshot_2021-01-07 Function Instance – Django REST framework](https://user-images.githubusercontent.com/12840061/103864350-62d4e700-50fd-11eb-8e66-8b4661ef4f09.png)

I think the dict text set in the above photo is correct. so basically, calling nuctl invoke openvino-dextr in terminal works, but not with django REST api.

**Comment by yaochenglouis** [comment]
I find that inside cvat container, entering by` docker exec --user root -it cvat bash`, 
with `apt-get install nmap`

`curl 172.17.0.1:49157` ( the listening port of dextr, I can access normally in chrome/firefox, or by curl in terminal of host)
cvat container gets time out.

and i did a scan with nmap inside cvat container: 
`nmap -vv -sS 172.17.0.1`
```
Starting Nmap 7.80 ( https://nmap.org ) at 2021-01-07 15:20 UTC
Initiating Ping Scan at 15:20
Scanning 172.17.0.1 [4 ports]
Completed Ping Scan at 15:20, 0.04s elapsed (1 total hosts)
Initiating Parallel DNS resolution of 1 host. at 15:20
Completed Parallel DNS resolution of 1 host. at 15:20, 0.00s elapsed
Initiating SYN Stealth Scan at 15:20
Scanning server301 (172.17.0.1) [1000 ports]
Discovered open port 3389/tcp on 172.17.0.1
Discovered open port 22/tcp on 172.17.0.1
Discovered open port 7070/tcp on 172.17.0.1
Completed SYN Stealth Scan at 15:20, 4.59s elapsed (1000 total ports)
Nmap scan report for server301 (172.17.0.1)
Host is up, received echo-reply ttl 64 (0.000077s latency).
Scanned at 2021-01-07 15:20:33 UTC for 4s
Not shown: 997 filtered ports
Reason: 997 no-responses
PORT     STATE SERVICE       REASON
22/tcp   open  ssh           syn-ack ttl 64
3389/tcp open  ms-wbt-server syn-ack ttl 64
7070/tcp open  realserver    syn-ack ttl 64

Read data files from: /usr/bin/../share/nmap
Nmap done: 1 IP address (1 host up) scanned in 4.81 seconds
           Raw packets sent: 2003 (88.108KB) | Rcvd: 6 (248B)
root@72bc33069d71:~# curl http://172.17.0.1:3389
curl: (1) Received HTTP/0.9 when not allowed

root@72bc33069d71:~# curl http://172.17.0.1:7070
curl: (52) Empty reply from server

```

**Comment by yaochenglouis** [comment]
I suppose that the port 49157 is not open for cvat container. trying to solve that

**Comment by yaochenglouis** [comment]
after disabling ufw, things went better. but i am having a new bug..

**Comment by yaochenglouis** [comment]
Final word: for those who use ufw, first find the port that your nuclio function listens to, and ufw allow port. that worked for me.

**Comment by JattKisaan** [comment]
I didn't know how to "find the port that your nuclio function listens to", as Yao put it. But I got lucky and noticed that, at least for Segment Anything Model, the port number appears in the Ports column of `docker ps`. Hope that helps someone.
