### ISSUE TITLE
new could not translate host name "cvat_db" to address

### ISSUE THREAD

**Issue by nicken** [openvinotoolkit/cvat#2665]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

I can open the `localhost:8080`,get page

### Current Behaviour

run `docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'`get this error info:
```shell
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'v1' isn't unique. You may not be able to reverse all URLs in this namespace
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "cvat_db" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 370, in execute
    self.check_migrations()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 459, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 216, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/opt/venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "cvat_db" to address: Temporary failure in name resolution

```
* `docker logs cvat_proxy`

```shell
2021/01/14 10:40:46 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
2021/01/14 10:40:51 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
2021/01/14 10:40:57 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
2021/01/14 10:41:03 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
2021/01/14 10:41:09 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
2021/01/14 10:41:16 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
2021/01/14 10:41:25 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
2021/01/14 10:41:37 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
2021/01/14 10:41:55 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
2021/01/14 10:42:26 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
2021/01/14 10:43:23 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
2021/01/14 10:44:29 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
2021/01/14 10:45:34 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
2021/01/14 10:46:40 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
2021/01/14 10:47:45 [emerg] 1#1: host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16
nginx: [emerg] host not found in upstream "cvat" in /etc/nginx/conf.d/default.conf:16

```

### Possible Solution

i try   solve this error to add `POSTGRES_HOST_AUTH_METHOD: 'trust'` in yaml from #1145, but i find in my yaml is using

### Steps to Reproduce (for bugs)

1. `docker-compose build`

   * docker-compose.yml

     >  I only change the http_proxy 、https_proxy、socks_proxy and add network_mode

   ```yaml
   #
   # Copyright (C) 2018-2020 Intel Corporation
   #
   # SPDX-License-Identifier: MIT
   #
   version: '3.3'
   
   services:
     cvat_db:
       container_name: cvat_db
       image: postgres:10-alpine
       networks:
         default:
           aliases:
             - db
       restart: always
       environment:
         POSTGRES_USER: root
         POSTGRES_DB: cvat
         POSTGRES_HOST_AUTH_METHOD: trust
       volumes:
         - cvat_db:/var/lib/postgresql/data
   
     cvat_redis:
       container_name: cvat_redis
       image: redis:4.0-alpine
       networks:
         default:
           aliases:
             - redis
       restart: always
   
     cvat:
       container_name: cvat
       image: cvat/server
       restart: always
       network_mode: "host"
       depends_on:
         - cvat_redis
         - cvat_db
       build:
         context: .
         args:
           http_proxy: "http://172.28.0.1:1090"
           https_proxy: "http://172.28.0.1:1090"
           no_proxy: nuclio,${no_proxy}
           socks_proxy: "http://172.28.0.1:1089"
           USER: 'django'
           DJANGO_CONFIGURATION: 'production'
           TZ: 'Etc/UTC'
           CLAM_AV: 'no'
       environment:
         DJANGO_MODWSGI_EXTRA_ARGS: ''
         ALLOWED_HOSTS: '*'
         CVAT_REDIS_HOST: 'cvat_redis'
         CVAT_POSTGRES_HOST: 'cvat_db'
       volumes:
         - cvat_data:/home/django/data
         - cvat_keys:/home/django/keys
         - cvat_logs:/home/django/logs
         - cvat_models:/home/django/models
   
     cvat_ui:
       container_name: cvat_ui
       image: cvat/ui
       restart: always
       build:
         context: .
         args:
           http_proxy: "http://172.28.0.1:1090"
           https_proxy: "http://172.28.0.1:1090"
           no_proxy: nuclio,${no_proxy}
           socks_proxy: "http://172.28.0.1:1089"
         dockerfile: Dockerfile.ui
   
       networks:
         default:
           aliases:
             - ui
       depends_on:
         - cvat
   
     cvat_proxy:
       container_name: cvat_proxy
       image: nginx:stable-alpine
       restart: always
       depends_on:
         - cvat
         - cvat_ui
       environment:
         CVAT_HOST: localhost
       ports:
         - '8080:80'
       volumes:
         - ./cvat_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
         - ./cvat_proxy/conf.d/cvat.conf.template:/etc/nginx/conf.d/cvat.conf.template:ro
       command: /bin/sh -c "envsubst '$$CVAT_HOST' < /etc/nginx/conf.d/cvat.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
   
   networks:
     default:
       ipam:
         driver: default
         config:
           - subnet: 172.28.0.0/24
   
   volumes:
     cvat_db:
     cvat_data:
     cvat_keys:
     cvat_logs:
     cvat_models:
   ```
2. docker-compose up -d
3. docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'
   

### Your Environment

- Git hash commit (`git log -1`):`commit 649f962bec43047cb70dc98ab77189ef64228ab9 `
- Docker version `docker version` (e.g. Docker 17.0.05): `Docker version 20.10.2, build 2291f61`

- Are you using Docker Swarm or Kubernetes?

- Operating System and version (e.g. Linux, Windows, MacOS): ubuntu18.04

- Code example or link to GitHub repo or gist to reproduce problem:

- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nicken** [comment]
when i remove `network_mode: "host"`, I find i can get page

**Comment by nicken** [comment]
sorry, i will close this
