### ISSUE TITLE
500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations

### ISSUE THREAD

**Issue by xs818818** [openvinotoolkit/cvat#2777]
I have 
http://localhost:8070/api/function_invocations
Can you tell me how to change nuclio to  localhost

**Comment by azhavoro** [comment]
@xs818818 sorry, I'm not sure that understand your question, please explain what is your issue exactly.

**Comment by davodogster** [comment]
@azhavoro  I have the same problem when I try to run IOG Interactor inside CVAT at my local IP. How did you fix it? @xs818818 

![image](https://user-images.githubusercontent.com/46079516/115491164-99e99580-a2b3-11eb-86c8-a038d50e3cea.png)

![image](https://user-images.githubusercontent.com/46079516/115491191-a4a42a80-a2b3-11eb-994c-538f63ebcc8b.png)

**Comment by sicoyle** [comment]
I also see this issue when running CVAT using Docker.

Here is the err message from the UI when I was trying to create an automatic annotation for a task:
`Fetching inference status for the task 2`
`Error: Inference status for the task 2 is failed. requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations`


Logs from cvat:
`2021-11-09 22:20:14,511 DEBG 'rqworker_low' stderr output:
ERROR - 2021-11-09 22:20:14,510 - worker - Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 506, in __call__
    LambdaJob._call_detector(function, db_task, labels, quality,
  File "/home/django/cvat/apps/lambda_manager/views.py", line 374, in _call_detector
    annotations = function.invoke(db_task, data={
  File "/home/django/cvat/apps/lambda_manager/views.py", line 208, in invoke
    response = self.gateway.invoke(self, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 78, in invoke
    return self._http(method="post", url='/api/function_invocations',
  File "/home/django/cvat/apps/lambda_manager/views.py", line 56, in _http
    reply.raise_for_status()
  File "/opt/venv/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 506, in __call__
    LambdaJob._call_detector(function, db_task, labels, quality,
  File "/home/django/cvat/apps/lambda_manager/views.py", line 374, in _call_detector
    annotations = function.invoke(db_task, data={
  File "/home/django/cvat/apps/lambda_manager/views.py", line 208, in invoke
    response = self.gateway.invoke(self, payload)
  File "/home/django/cvat/apps/lambda_manager/views.py", line 78, in invoke
    return self._http(method="post", url='/api/function_invocations',
  File "/home/django/cvat/apps/lambda_manager/views.py", line 56, in _http
    reply.raise_for_status()
  File "/opt/venv/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://nuclio:8070/api/function_invocations`

Is the issue worth reopening at this point?

**Comment by 104H** [comment]
Was this issue resolved? I have the same problem. My requests go to nuclio:8070 instead of localhost:8070

**Comment by bhargav-sudo** [comment]
> @azhavoro I have the same problem when I try to run IOG Interactor inside CVAT at my local IP. How did you fix it? @xs818818
> 
> ![image](https://user-images.githubusercontent.com/46079516/115491164-99e99580-a2b3-11eb-86c8-a038d50e3cea.png)
> 
> ![image](https://user-images.githubusercontent.com/46079516/115491191-a4a42a80-a2b3-11eb-994c-538f63ebcc8b.png)

Is this issue solved..? I am facing this issue.

**Comment by nmanovic** [comment]
@bhargav-sudo , please try http://github.com/cvat-ai/cvat. We changed the way how serverless functions were called.

https://github.com/cvat-ai/cvat/commit/ff30b776cf8da5b072d93163026661332193c3fc. Need to update the nuclio till 1.8.14. Please read the guide: https://cvat-ai.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/

**Comment by tdhooghe** [comment]
@nmanovic is it possible to migrate from opencv/cvat to cvat-ai/cvat?

**Comment by tdhooghe** [comment]
@nmanovic never mind, I found it here https://cvat-ai.github.io/cvat/docs/faq/
