### ISSUE TITLE
Assertion error while uploading "cvat for videos"

### ISSUE THREAD

**Issue by PMazarovich** [openvinotoolkit/cvat#2814]
### My actions before raising this issue
- [x] Discussed this with developer in gitter

### Current Behaviour
I has some annotated video in one deployment and I am willing to copy this video with annotations on other one. So, I dumped annotations as cvat for video from old and uploaded them to the new. And here is an error.
Other formats like "cvat for images" or "labelme" works fine. 
[annotations.zip](https://github.com/openvinotoolkit/cvat/files/5988295/annotations.zip)

### Your Environment
CVAT version 1.2.0 on both deployments

### Error log
```
ERROR:rq.worker:Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 758, in import_task_annotations
    task.import_annotations(f, importer)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 641, in import_annotations
    importer(src_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 570, in _import
    load(p, task_data)
  File "/home/django/cvat/apps/dataset_manager/formats/cvat.py", line 517, in load
    annotations.add_track(track)
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 404, in add_track
    self._call_callback()
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 385, in _call_callback
    self._create_callback(self._annotation_ir.serialize())
  File "/home/django/cvat/apps/dataset_manager/task.py", line 600, in create
    self._patch_data(data, PatchAction.CREATE)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 590, in _patch_data
    self._merge_data(_data, jobs[jid]["start"], self.db_task.overlap)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 594, in _merge_data
    annotation_manager.merge(data, start_frame, overlap)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 149, in merge
    tracks.merge(data.tracks, start_frame, overlap)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 233, in merge
    cost_matrix[i][j] = 1 - self._calc_objects_similarity(
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 388, in _calc_objects_similarity
    obj1_shapes = TrackManager.get_interpolated_shapes(obj1, start_frame, end_frame)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 737, in get_interpolated_shapes
    assert shape["frame"] > curr_frame
AssertionError
```

**Comment by azhavoro** [comment]
@PMazarovich I can't find the related error logs in gitter, could you please attach them as well?

**Comment by PMazarovich** [comment]
Error log added

**Comment by zhiltsov-max** [comment]
@PMazarovich, I've failed to reproduce this error. I've created a task with 18300 frames of size 1280x720, segment size 1000 and overlap 5. Annotations were imported after few minutes. Commit id 98e2bf40ac0afeae99b46feeb8016503f4b1699c (read as current develop after 1.2.0).
![image](https://user-images.githubusercontent.com/13832349/109798705-25d42f00-7c2c-11eb-93a1-b22b36185ce0.png)

**Comment by nmanovic** [comment]
@PMazarovich , could you please confirm that the issue was fixed? Look at the comment from @zhiltsov-max

**Comment by PMazarovich** [comment]
@zhiltsov-max , @nmanovic , Thanks for checking, I updated the project and now it is working!
