### ISSUE TITLE
[Bug] The 'ValueError: Unknown internal frame' error at dump annotations.

### ISSUE THREAD

**Issue by DmitriyOparin** [openvinotoolkit/cvat#2827]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Annotations was downloaded. 
Error message is not present.

### Current Behaviour
Annotations was not downloaded. 
The 'ValueError: Unknown internal frame' error message is present.

### Possible Solution
Fix the bug.

### Steps to Reproduce (for bugs)
1. Create task with parametrs:
    * select 10 images
    * set Overlap size = 3
    * set Segment size = 6
2. Create rectangle (track) annotation in penultimate job 
3. Dump CVAT for images 1.1 annotations

### Your Environment

- Git hash commit (`git log -1`):  e382313df99b3a613f1f16d1e4d36dd2e191b5f4
- Docker version `docker version` (e.g. Docker 17.0.05): N/A
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

> Traceback (most recent call last):
  File "/home/diman/.local/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/home/diman/.local/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/home/diman/.local/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/views.py", line 87, in export_task_annotations
    return export_task(task_id, dst_format, server_url=server_url, save_images=False)
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/views.py", line 61, in export_task
    task.export_task(task_id, temp_file, dst_format,
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/task.py", line 749, in export_task
    task.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/task.py", line 631, in export
    exporter(dst_file, task_data, **options)
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/formats/registry.py", line 37, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/formats/cvat.py", line 559, in _export_images
    _export(dst_file, task_data,
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/formats/cvat.py", line 531, in _export
    anno_callback(f, task_data)
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/formats/cvat.py", line 179, in dump_as_cvat_annotation
    for frame_annotation in annotations.group_by_frame(include_empty=True):
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/bindings.py", line 273, in group_by_frame
    exported_shape = self._export_tracked_shape(shape)
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/bindings.py", line 211, in _export_tracked_shape
    frame=self.abs_frame_id(shape["frame"]),
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/bindings.py", line 106, in abs_frame_id
    raise ValueError("Unknown internal frame id %s" % relative_id)
ValueError: Unknown internal frame id 10

![image_2021_02_17T15_43_41_527Z](https://user-images.githubusercontent.com/35344996/108228717-2f4f9880-7150-11eb-869d-0f9404cd3354.png)

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@zhiltsov-max , could you please look at the issue?
