### ISSUE TITLE
[Bug] Exception 'key must be a task identifier' does not handle.

### ISSUE THREAD

**Issue by DmitriyOparin** [openvinotoolkit/cvat#2839]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Response returned with status code = 400 Bad Requests.

### Current Behaviour
Exception: 456 key must be a task identifier

### Possible Solution
Fix the bug.

### Steps to Reproduce (for bugs)
1. Create GET query to /api/v1/tasks/456/data?type=chunk&number=1quality=compressed (wrong number task)

### Your Environment

- Git hash commit (`git log -1`): dc4760aeb1fbc0491bb642d51b0c8a1fe402ddf9
- Docker version `docker version` (e.g. Docker 17.0.05): N/A
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

> Traceback (most recent call last):
  File "/home/diman/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/diman/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/diman/.local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/diman/.local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/diman/.local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/diman/.local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/diman/.local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/diman/.local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/diman/git/cvat/cvat/apps/engine/views.py", line 509, in data
    slogger.task[pk].error(msg, exc_info=True)
  File "/home/diman/git/cvat/cvat/apps/engine/log.py", line 55, in __getitem__
    self._storage[tid] = self._create_task_logger(tid)
  File "/home/diman/git/cvat/cvat/apps/engine/log.py", line 59, in _create_task_logger
    task = _get_task(tid)
  File "/home/diman/git/cvat/cvat/apps/engine/log.py", line 19, in _get_task
    raise Exception('{} key must be a task identifier'.format(tid))
Exception: 456 key must be a task identifier

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@azhavoro , could you please take care of the problem?
