### ISSUE TITLE
[Bug] The "AttributeError: 'NoneType' object has no attribute 'astype'\n" error at upload CamVid 1.0 annotations.

### ISSUE THREAD

**Issue by DmitriyOparin** [openvinotoolkit/cvat#2840]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Error does not present. 
Annotations uploaded.

### Current Behaviour

Error present.
Annotations did not upload.

### Possible Solution

Fix this bug.

### Steps to Reproduce (for bugs)

1. Create task with several images (jpeg)
1. Draw rectangle (shape) in first frames
1. Dump CamVid 1.0 annotations.
1. Upload CamVid 1.0 annotations.

### Your Environment

- Git hash commit (`git log -1`): 16d7f3ce016a45636ea419f24c8b34284765fb28
- Docker version `docker version` (e.g. Docker 17.0.05): N/A
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

Logs from server RQ - default:

> Traceback (most recent call last):
  File "/home/diman/.local/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/home/diman/.local/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/home/diman/.local/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/task.py", line 767, in import_job_annotations
    job.import_annotations(f, importer)
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/task.py", line 556, in import_annotations
    importer(src_file, task_data)
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/formats/registry.py", line 37, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/diman/git/cvat/cvat/apps/dataset_manager/formats/camvid.py", line 39, in _import
    dataset = dm_env.make_importer('camvid')(tmp_dir).make_dataset()
  File "/home/diman/.local/lib/python3.8/site-packages/datumaro/components/project.py", line 342, in make_dataset
    return ProjectDataset(self)
  File "/home/diman/.local/lib/python3.8/site-packages/datumaro/components/project.py", line 35, in __init__
    sources[s_name] = Dataset.import_from(url,
  File "/home/diman/.local/lib/python3.8/site-packages/datumaro/components/dataset.py", line 273, in import_from
    extractors.append(env.make_extractor(
  File "/home/diman/.local/lib/python3.8/site-packages/datumaro/components/environment.py", line 270, in make_extractor
    return self.extractors.get(name)(*args, **kwargs)
  File "/home/diman/.local/lib/python3.8/site-packages/datumaro/plugins/camvid_format.py", line 143, in __init__
    self._items = list(self._load_items(path).values())
  File "/home/diman/.local/lib/python3.8/site-packages/datumaro/plugins/camvid_format.py", line 173, in _load_items
    mask = mask()
  File "/home/diman/.local/lib/python3.8/site-packages/datumaro/util/image.py", line 180, in __call__
    image = self.loader(self.path)
  File "/home/diman/.local/lib/python3.8/site-packages/datumaro/util/mask_tools.py", line 116, in <lambda>
    return lazy_image(path, lambda path: load_mask(path, inverse_colormap))
  File "/home/diman/.local/lib/python3.8/site-packages/datumaro/util/mask_tools.py", line 109, in load_mask
    mask = load_image(path, dtype=np.uint8)
  File "/home/diman/.local/lib/python3.8/site-packages/datumaro/util/image.py", line 34, in load_image
    image = image.astype(dtype)
AttributeError: 'NoneType' object has no attribute 'astype'

![image](https://user-images.githubusercontent.com/35344996/108595534-7082bb00-7391-11eb-8882-d74dd8c34559.png)

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@yasakova-anastasia , could you please investigate?
