### ISSUE TITLE
Dump annotations in COCO format fails: Error: Request failed with status code 500. "KeyError: 'coco_instances'\n".

### ISSUE THREAD

**Issue by ophir-oneview** [openvinotoolkit/cvat#2845]
_Hi first of all this project is amazing and very useful thanks:)_ 

### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

I am trying to download annotations in COCO format,
Click on Dump annotations pick COCO 1.0 should download the COCO.json file

### Current Behaviour

Click on Dump annotations pick COCO 1.0 raises an Error:
`Error: Request failed with status code 500. "KeyError: 'coco_instances'\n".`
This occurred only in COCO format. download in CVAT format works

### Steps to Reproduce (for bugs)

1. upgrade to v1.2.0
2. open a new project 
3. annotate 
4. try to dump the annotations to COCO file

### Context

This happened to us after upgrade to version 1.2.0.

### Your Environment

- commit 37d82f90052ab26c584dfb2c87a4623cb22e0ff4 
- Client: Docker Engine - Community
 Version:           19.03.12
<details>
<summary>docker version full </summary>
Version:           19.03.12

 API version:       1.40

Go version:        go1.13.10

Git commit:        48a66213fe

Built:             Mon Jun 22 15:45:36 2020

 OS/Arch:           linux/amd64

 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
 </details>

- Are you using Docker Swarm or Kubernetes? No

- Operating System and version (e.g. Linux, Windows, MacOS): Linux (Ubuntu 18.04.4 LTS)

**Comment by ophir-oneview** [comment]
`Docker logs cvat ` output:
```
2021-02-23 09:24:19,982 DEBG 'rqworker_default_0' stderr output:
INFO:rq.worker:default: cvat.apps.dataset_manager.views.export_task_annotations(93, 'COCO 1.0', 'http://XXXXXXX:8080') (/api/v1/tasks/93/annotations/COCO 1.0)

2021-02-23 09:24:19,984 DEBG 'rqworker_default_0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2021-02-23 09:24:19,991 DEBG 'rqworker_default_0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 90 seconds.

2021-02-23 09:24:22,458 DEBG 'rqworker_default_0' stderr output:
[2021-02-23 09:24:22,457] ERROR cvat.server.task_93: [cvat.apps.dataset_manager.views @ export_task]: exception occurred
Traceback (most recent call last):
  File "/home/django/cvat/apps/dataset_manager/views.py", line 61, in export_task
    task.export_task(task_id, temp_file, dst_format,
  File "/home/django/cvat/apps/dataset_manager/task.py", line 749, in export_task
    task.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 631, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/coco.py", line 21, in _export
    dm_env.converters.get('coco_instances').convert(extractor,
  File "/opt/venv/lib/python3.8/site-packages/datumaro/components/project.py", line 60, in get
    return self.items[key] # returns a class / ctor
KeyError: 'coco_instances'

2021-02-23 09:24:22,459 DEBG 'rqworker_default_0' stderr output:
ERROR:cvat.server.task_93:[cvat.apps.dataset_manager.views @ export_task]: exception occurred
Traceback (most recent call last):
  File "/home/django/cvat/apps/dataset_manager/views.py", line 61, in export_task
    task.export_task(task_id, temp_file, dst_format,
  File "/home/django/cvat/apps/dataset_manager/task.py", line 749, in export_task
    task.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 631, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/coco.py", line 21, in _export
    dm_env.converters.get('coco_instances').convert(extractor,
  File "/opt/venv/lib/python3.8/site-packages/datumaro/components/project.py", line 60, in get
    return self.items[key] # returns a class / ctor
KeyError: 'coco_instances'

2021-02-23 09:24:22,459 DEBG 'rqworker_default_0' stderr output:
DEBUG:rq.worker:Handling failed execution of job /api/v1/tasks/93/annotations/COCO 1.0

2021-02-23 09:24:22,461 DEBG 'rqworker_default_0' stderr output:
ERROR:rq.worker:Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 87, in export_task_annotations
    return export_task(task_id, dst_format, server_url=server_url, save_images=False)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 61, in export_task
    task.export_task(task_id, temp_file, dst_format,
  File "/home/django/cvat/apps/dataset_manager/task.py", line 749, in export_task
    task.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 631, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/coco.py", line 21, in _export
    dm_env.converters.get('coco_instances').convert(extractor,
  File "/opt/venv/lib/python3.8/site-packages/datumaro/components/project.py", line 60, in get
    return self.items[key] # returns a class / ctor
KeyError: 'coco_instances'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 87, in export_task_annotations
    return export_task(task_id, dst_format, server_url=server_url, save_images=False)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 61, in export_task
    task.export_task(task_id, temp_file, dst_format,
  File "/home/django/cvat/apps/dataset_manager/task.py", line 749, in export_task
    task.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 631, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/coco.py", line 21, in _export
    dm_env.converters.get('coco_instances').convert(extractor,
  File "/opt/venv/lib/python3.8/site-packages/datumaro/components/project.py", line 60, in get
    return self.items[key] # returns a class / ctor
KeyError: 'coco_instances'

2021-02-23 09:24:22,461 DEBG 'rqworker_default_0' stderr output:
DEBUG:rq.worker:Invoking exception handler <function rq_handler at 0x7fcb49ee4940>

2021-02-23 09:24:22,476 DEBG 'rqworker_default_0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2021-02-23 09:24:22,476 DEBG 'rqworker_default_0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2021-02-23 09:24:22,477 DEBG 'rqworker_default_0' stderr output:
DEBUG:rq.worker:*** Listening on default...

2021-02-23 09:24:22,477 DEBG 'rqworker_default_0' stderr output:
DEBUG:rq.worker:Sent heartbeat to prevent worker timeout. Next one should arrive within 480 seconds.

2021-02-23 09:24:23,202 DEBG 'runserver' stderr output:
[Tue Feb 23 09:24:23.202729 2021] [wsgi:error] [pid 171:tid 139657896933120] [remote 172.28.0.6:51626] [2021-02-23 09:24:23,202] ERROR django.request: Internal Server Error: /api/v1/tasks/93/annotations

2021-02-23 09:24:23,203 DEBG 'runserver' stderr output:
[Tue Feb 23 09:24:23.203378 2021] [wsgi:error] [pid 171:tid 139657896933120] [remote 172.28.0.6:51626] ERROR:django.request:Internal Server Error: /api/v1/tasks/93/annotations

```

**Comment by nmanovic** [comment]
@yasakova-anastasia , could you please look at the issue?

**Comment by ophir-oneview** [comment]
Hi @nmanovic,
Thanks for the reply.
I tried to upgrade to the HEAD on develop branch and it looks like it fixes the bug.
commit: 268abcbe51fdc6b699e9964fadfd8cb271667cbc
Not sure what it was probably some commits before :) ...

Ophir

**Comment by nmanovic** [comment]
@ophir-oneview , thanks for the feedback. We will close the issue in this case.
