### ISSUE TITLE
Error: Request failed with status code 502

### ISSUE THREAD

**Issue by Diaislam** [openvinotoolkit/cvat#3006]
Hello, Cvat was working fine until suddenly went down and couldn't restart it at first i thought its a space problem ,but even after freeing some space nothing happens i get this error in cvat logs 

Traceback (most recent call last):
  File "/usr/bin/supervisord", line 11, in <module>
    load_entry_point('supervisor==4.1.0', 'console_scripts', 'supervisord')()
  File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 358, in main
    go(options)
  File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 368, in go
    d.main()
  File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 76, in main
    self.run()
  File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 84, in run
    self.add_process_group(config)
  File "/usr/lib/python3/dist-packages/supervisor/supervisord.py", line 116, in add_process_group
    config.after_setuid()
  File "/usr/lib/python3/dist-packages/supervisor/options.py", line 1981, in after_setuid
    config.create_autochildlogs()
  File "/usr/lib/python3/dist-packages/supervisor/options.py", line 1889, in create_autochildlogs
    self.stdout_logfile = get_autoname(name, sid, 'stdout')
  File "/usr/lib/python3/dist-packages/supervisor/options.py", line 1261, in get_autochildlog_name
    logfile = self.mktempfile(
  File "/usr/lib/python3/dist-packages/supervisor/options.py", line 1514, in mktempfile
    fd, filename = tempfile.mkstemp(suffix, prefix, dir)
  File "/usr/lib/python3.8/tempfile.py", line 471, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.8/tempfile.py", line 389, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/home/django/logs/ssh-agent-stdout---supervisor-0_i87h6v.log'

the ui is showing but stuck at logging page : with this error 502

Tried changing allowed host and all solutions i found but no help

i even cloned the repo and rebuilt again but seems not working.
when trying to use this command 
docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'
for creating super user i got this error

Error response from daemon: Container 9e97c3780ba508d486254f0fc65fc6bcc531563a73f13f9ff1cd32756018b4bf is restarting, wait until the container is running

**Comment by azhavoro** [comment]
Discussed and solved in Gitter.
`cvat_logs` volume must have write permissions for uid 1000.
