### ISSUE TITLE
When I clicked the link "Job#1",  the browser doesn't pop up the annotation page.

### ISSUE THREAD

**Issue by x505367603** [openvinotoolkit/cvat#3055]
TypeError
e.html(...).removeEventListener is not a function

TypeError: e.html(...).removeEventListener is not a function
    at Ob.componentWillUnmount (http://localhost:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:404:866773)
    at http://localhost:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:84509
    at is (http://localhost:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:84550)
    at us (http://localhost:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:86385)
    at pl (http://localhost:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:99857)
    at t.unstable_runWithPriority (http://localhost:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:364:3844)
    at Ba (http://localhost:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:45023)
    at fl (http://localhost:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:97717)
    at Qs (http://localhost:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:93871)
    at http://localhost:8080/cvat-ui.2cce2fa422a65445a9c6.min.js:356:45314

**Comment by bsekachev** [comment]
@x505367603 

Please, fill out the issue template properly

**Comment by nmanovic** [comment]
@x505367603 , if you have more information about the problem, please reopen the issue.
