### ISSUE TITLE
Error: Can not push to remote repository. Message: IndexError: No item found with id 'master'

### ISSUE THREAD

**Issue by loukbabi** [openvinotoolkit/cvat#3190]
### My actions before raising this issue
- [yes] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [yes] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Declare a new task
1. Set a Dataset repository URL to my private github repo
1. Provide my github account with the prompt public key

### Context
I would like to use the provided functionality of attaching a repository to store annotations there. However, when I click the Synchronize button, I am getting an error: Error: Can not push to remote repository. Message: IndexError: No item found with id 'master'.

### Your Environment

- Git hash commit (`git log -1`): 7a4980619ccb1c8896ba1a0b948225ffd3864195
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.6
- Operating System and version (e.g. Linux, Windows, MacOS): Linux 18.06

**Comment by bsekachev** [comment]
Hi @loukbabi 

Does the attached repository have master branch?

**Comment by loukbabi** [comment]
Thank you for your response. Yes, it does.

**Comment by bsekachev** [comment]
@loukbabi 

Could you please also attach an output of ``docker logs cvat``. There should be exception error with a stack. Try to collect it after the error occurs on UI.

**Comment by bsekachev** [comment]
No response, so I will close the issue for now. If you still have it, do not hesitate to reopen it.

**Comment by niclaswue** [comment]
I get the same error when pushing to a local GitLab repository. By default, the first branch is named "main", however I created the branch master and it is visible in the web interface. The relevant output of `docker logs cvat` is the following:

```2021-11-15 15:56:40,610 DEBG 'rqworker_default_1' stderr output:
INFO - 2021-11-15 15:56:40,609 - dataset_repo - User config initialization..

2021-11-15 15:56:40,634 DEBG 'rqworker_default_1' stderr output:
[2021-11-15 15:56:40,633] ERROR cvat.server.task_4: push to remote repository errors occured
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/git/util.py", line 881, in __getitem__
    return getattr(self, index)
  File "/opt/venv/lib/python3.8/site-packages/git/util.py", line 874, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'master'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 401, in push
    _git.push(user, scheme, host, db_task, db_task.updated_date)
  File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 237, in push
    self._pull()
  File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 198, in _pull
    self._rep.head.reference = self._rep.heads["master"]
  File "/opt/venv/lib/python3.8/site-packages/git/util.py", line 883, in __getitem__
    raise IndexError("No item found with id %r" % (self._prefix + index)) from e
IndexError: No item found with id 'master'

2021-11-15 15:56:40,634 DEBG 'rqworker_default_1' stderr output:
ERROR - 2021-11-15 15:56:40,633 - dataset_repo - push to remote repository errors occured
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/git/util.py", line 881, in __getitem__
    return getattr(self, index)
  File "/opt/venv/lib/python3.8/site-packages/git/util.py", line 874, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'master'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 401, in push
    _git.push(user, scheme, host, db_task, db_task.updated_date)
  File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 237, in push
    self._pull()
  File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 198, in _pull
    self._rep.head.reference = self._rep.heads["master"]
  File "/opt/venv/lib/python3.8/site-packages/git/util.py", line 883, in __getitem__
    raise IndexError("No item found with id %r" % (self._prefix + index)) from e
IndexError: No item found with id 'master'

2021-11-15 15:56:40,636 DEBG 'rqworker_default_1' stderr output:
DEBUG - 2021-11-15 15:56:40,636 - worker - Handling failed execution of job git.push.4

2021-11-15 15:56:40,638 DEBG 'rqworker_default_1' stderr output:
ERROR - 2021-11-15 15:56:40,638 - worker - Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/git/util.py", line 881, in __getitem__
    return getattr(self, index)
  File "/opt/venv/lib/python3.8/site-packages/git/util.py", line 874, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'master'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 411, in push
    raise ex
  File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 401, in push
    _git.push(user, scheme, host, db_task, db_task.updated_date)
  File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 237, in push
    self._pull()
  File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 198, in _pull
    self._rep.head.reference = self._rep.heads["master"]
  File "/opt/venv/lib/python3.8/site-packages/git/util.py", line 883, in __getitem__
    raise IndexError("No item found with id %r" % (self._prefix + index)) from e
IndexError: No item found with id 'master'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/git/util.py", line 881, in __getitem__
    return getattr(self, index)
  File "/opt/venv/lib/python3.8/site-packages/git/util.py", line 874, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'master'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 411, in push
    raise ex
  File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 401, in push
    _git.push(user, scheme, host, db_task, db_task.updated_date)
  File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 237, in push
    self._pull()
  File "/home/django/cvat/apps/dataset_repo/dataset_repo.py", line 198, in _pull
    self._rep.head.reference = self._rep.heads["master"]
  File "/opt/venv/lib/python3.8/site-packages/git/util.py", line 883, in __getitem__
    raise IndexError("No item found with id %r" % (self._prefix + index)) from e
IndexError: No item found with id 'master'
```

**Comment by bsekachev** [comment]
Hmm, maybe it is related with the fact, that default ``master`` branch was renamed to ``main`` 
https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

**Comment by niclaswue** [comment]
Maybe, I just tested deleting the `main` branch, just keeping `master` as the default branch. However, the error stays the same.

**Comment by niclaswue** [comment]
Ok, I just tried again today and the error was, that I did not include a filepath. The format has to be something like: `http://server.xyz/user/repo [annotations/labels.zip]` it is not enough to just put `http://server.xyz/user/repo`. Somehow I thought the path in the brackets was optional. Anyways, this should be documented or at least a more descriptive error should be raised.

**Comment by niclaswue** [comment]
This issue may be related to GitLab. When using GitHub, it works without the filepath. I think a different behavior is not desired here and the issue should be reopened.
