### ISSUE TITLE
Bug in case lack of objects while saving in AAM

### ISSUE THREAD

**Issue by TOsmanov** [openvinotoolkit/cvat#3266]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Saving the task without bugs.

### Current Behaviour

If you save the task when the label of an object was changed in Attribute Annotation Mode with a filter applied to a specific label, then CVAT closes with the error “Oops, something went wrong”.

### Steps to Reproduce (for bugs)

1. Add filter (example label == “label_name”)
1. Change annotation mode to Attribute Annotation Mode
1. Change the label to any other. Thus, there should be no objects that meet the filter.
1. Save

### Context

Saving occurs, but the bug forces you to reboot the page

### Your Environment

- Windows 10, Google Chrome, 
- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>TypeError
Cannot read property 'objectType' of undefined

TypeError: Cannot read property 'objectType' of undefined
    at Ew.activateOnCanvas (https://cvat.org/cvat-ui.619e2cab9c511e1a12c4.min.js:414:998304)
    at Ew.componentDidUpdate (https://cvat.org/cvat-ui.619e2cab9c511e1a12c4.min.js:414:996061)
    at os (https://cvat.org/cvat-ui.619e2cab9c511e1a12c4.min.js:352:83470)
    at pl (https://cvat.org/cvat-ui.619e2cab9c511e1a12c4.min.js:352:101245)
    at t.unstable_runWithPriority (https://cvat.org/cvat-ui.619e2cab9c511e1a12c4.min.js:360:3844)
    at Ba (https://cvat.org/cvat-ui.619e2cab9c511e1a12c4.min.js:352:45023)
    at fl (https://cvat.org/cvat-ui.619e2cab9c511e1a12c4.min.js:352:97717)
    at Qs (https://cvat.org/cvat-ui.619e2cab9c511e1a12c4.min.js:352:93871)
    at https://cvat.org/cvat-ui.619e2cab9c511e1a12c4.min.js:352:45314
    at t.unstable_runWithPriority (https://cvat.org/cvat-ui.619e2cab9c511e1a12c4.min.js:360:3844)
    </summary>
    </details> 

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by bsekachev** [comment]
> Change the label to any other. Thus, there should be no objects that meet the filter.

Yes, it is true. But it was intentioned that after the object was changed it is still visible because of UX reasons (the change can be done accidentally or it is not finished yet when we are changing the text for example). In these cases, we should not immediately hide the object.

The issue fixed in the PR below.
