### ISSUE TITLE
Cvat debugger model latest update issues

### ISSUE THREAD

**Issue by KALALRANJITHKUMAR** [openvinotoolkit/cvat#3340]
(.env) root@ip-172-31-73-231:/home/ubuntu/cvat# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/cvat/cvat/urls.py", line 27, in <module>
    path('', include('cvat.apps.engine.urls')),
  File "/home/ubuntu/cvat/.env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/cvat/cvat/apps/engine/urls.py", line 7, in <module>
    from . import views
  File "/home/ubuntu/cvat/cvat/apps/engine/views.py", line 1180
    if (provider_type := self.request.query_params.get('provider_type', None)):
                      ^
SyntaxError: invalid syntax

**Comment by bsekachev** [comment]
I see operator ``:=`` which was added in Python 3.8. But CVAT supports Python 3.6 according to CONTRIBUTING.md, so I suppose it is a bug. 

@Marishka17, did you write this file?

**Comment by Marishka17** [comment]
> I see operator `:=` which was added in Python 3.8. But CVAT supports Python 3.6 according to CONTRIBUTING.md, so I suppose it is a bug.
> 
> @Marishka17, did you write this file?

Fixed in [PR](https://github.com/openvinotoolkit/cvat/pull/3336)
