### ISSUE TITLE
Cannot read property 'newLabelName' of undefined 

### ISSUE THREAD

**Issue by bsekachev** [openvinotoolkit/cvat#3403]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Issue in ``/cvat/cvat-ui/src/components/move-task-modal/label-mapper-item.tsx``
or ``/cvat/cvat-ui/src/components/move-task-modal/move-task-modal.tsx``

Source file: https://cvat.org/cvat-ui.386a8e3f86ebee8b4a71.min.js
Line: 414
Error count: 2
Stack:

TypeError: Cannot read property 'newLabelName' of undefined
    at Wb (https://cvat.org/cvat-ui.386a8e3f86ebee8b4a71.min.js:414:934308)
    at Ko (https://cvat.org/cvat-ui.386a8e3f86ebee8b4a71.min.js:352:57930)
    at gs (https://cvat.org/cvat-ui.386a8e3f86ebee8b4a71.min.js:352:104169)
    at cl (https://cvat.org/cvat-ui.386a8e3f86ebee8b4a71.min.js:352:96717)
    at sl (https://cvat.org/cvat-ui.386a8e3f86ebee8b4a71.min.js:352:96642)
    at Qs (https://cvat.org/cvat-ui.386a8e3f86ebee8b4a71.min.js:352:93672)
    at https://cvat.org/cvat-ui.386a8e3f86ebee8b4a71.min.js:352:45314
    at t.unstable_runWithPriority (https://cvat.org/cvat-ui.386a8e3f86ebee8b4a71.min.js:360:3844)
    at Ba (https://cvat.org/cvat-ui.386a8e3f86ebee8b4a71.min.js:352:45023)
    at Ga (https://cvat.org/cvat-ui.386a8e3f86ebee8b4a71.min.js:352:45259)

### Expected Behaviour
No exceptions and UI fails

### Current Behaviour
We get exception messages from cvat.org

### Possible Solution
Fix the bug

### Steps to Reproduce (for bugs)

1. Not investigated

**Comment by bsekachev** [comment]
@ActiveChooN 
It can be reproduced when we try to move 2nd task from tasks page to a project.
1. Open the task page
2. Move the first task to a project (one label), success
3. Move the second task to the project (one label), UI fails

If update a page, the 2nd task can be also successfuly moved. But in this case 3rd task causes the issue.
