### ISSUE TITLE
Add notification if the browser does not support some features (ResizeObserver, Object.fromEntries,...)

### ISSUE THREAD

**Issue by nkrot** [openvinotoolkit/cvat#3429]
This is my first time using CVAT. I installed the version v1.4.0.
I have logged into web ui, created a project and now that I m trying to create a task (as show in the screencast), I experience something weird.

1) when creating a new task, if I drag-and-drop images, the task is created. But then happens 3)

2) alternatively, when creating a new task, if I add files via file open dialog, I get a pop up error:

```
Could not create a task
TypeError: Object.fromEntries is not a function
```

3) assuming that the task was created as in step 1, i log in as a different user that is assigned to the task, and start annotating, i immediately get the following error:

```
TypeError: Object.fromEntries is not a function
    at http://192.168.20.101:8080/cvat-ui.6b2ae289a73efc92057f.min.js:414:915264
    at Ko (http://192.168.20.101:8080/cvat-ui.6b2ae289a73efc92057f.min.js:352:57930)
    at Ri (http://192.168.20.101:8080/cvat-ui.6b2ae289a73efc92057f.min.js:352:66791)
    at Ni (http://192.168.20.101:8080/cvat-ui.6b2ae289a73efc92057f.min.js:352:66610)
    at Ai (http://192.168.20.101:8080/cvat-ui.6b2ae289a73efc92057f.min.js:352:66293)
    at gs (http://192.168.20.101:8080/cvat-ui.6b2ae289a73efc92057f.min.js:352:107698)
    at cl (http://192.168.20.101:8080/cvat-ui.6b2ae289a73efc92057f.min.js:352:96717)
    at sl (http://192.168.20.101:8080/cvat-ui.6b2ae289a73efc92057f.min.js:352:96642)
    at Qs (http://192.168.20.101:8080/cvat-ui.6b2ae289a73efc92057f.min.js:352:93672)
    at http://192.168.20.101:8080/cvat-ui.6b2ae289a73efc92057f.min.js:352:45314
```

### Environment

1. version installed is v1.4.0 , `git log -1` shows

```
commit 315c9cc8d2b1c8fbd3b6b5e6ab6fca3a792bc895 (HEAD -> cvat-1.4.0, tag: v1.4.0, origin/master)
Merge: c7033a79 3ca86bcf
Author: Nikita Manovich <nikita.manovich@intel.com>
Date:   Wed May 19 07:26:02 2021 +0300

    Merge branch 'release-1.4.0'
```

2. the app is running on ubuntu 18.04.4 LTS (Bionic Beaver)
3. docker version 19.03.6
4. testing using Chrome Version 72.0.3626.109 (Official Build) (64-bit) from Mac OS Big Shit

**Comment by bsekachev** [comment]
@nkrot 

``Object.fromEntries`` [was introduced](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries) in Chrome 73. So, please update your browser.

**Comment by nkrot** [comment]
@bsekachev , thank you. Indeed, it works as expected in Chrome 91.0
