### ISSUE TITLE
Program Error when clicking on "Job" in Task

### ISSUE THREAD

**Issue by silvanro** [openvinotoolkit/cvat#3816]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour
Klicking on the "Job" link in a task should open the images to annotate

### Current Behaviour
Klicking on the "Job" link generates an Error "Oops, something went wrong
More likely there are some issues with the tool" 

TypeError
e.html(...).removeEventListener is not a function

TypeError: e.html(...).removeEventListener is not a function
    at Ob.componentWillUnmount (http://<adress_on_openshift_server>/cvat-ui.2cce2fa422a65445a9c6.min.js:404:866773)
    at http://<adress_on_openshift_server>/cvat-ui.2cce2fa422a65445a9c6.min.js:356:84509
    at is (http://<adress_on_openshift_server>/cvat-ui.2cce2fa422a65445a9c6.min.js:356:84550)
    at us (http://<adress_on_openshift_server>/cvat-ui.2cce2fa422a65445a9c6.min.js:356:86385)
    at pl (http://<adress_on_openshift_server>/cvat-ui.2cce2fa422a65445a9c6.min.js:356:99857)
    at t.unstable_runWithPriority (http://<adress_on_openshift_server>/cvat-ui.2cce2fa422a65445a9c6.min.js:364:3844)
    at Ba (http://<adress_on_openshift_server>/cvat-ui.2cce2fa422a65445a9c6.min.js:356:45023)
    at fl (http://<adress_on_openshift_server>/cvat-ui.2cce2fa422a65445a9c6.min.js:356:97717)
    at Qs (http://<adress_on_openshift_server>/cvat-ui.2cce2fa422a65445a9c6.min.js:356:93871)
    at http://<adress_on_openshift_server>/cvat-ui.2cce2fa422a65445a9c6.min.js:356:45314

### Steps to Reproduce (for bugs)
don't know :/

### Your Environment

Deployment on Openshift

CVAT version
Server: 1.2
Core: 3.12.0
Canvas: 2.4.1
UI: 1.18.1

**Comment by silvanro** [comment]
It worked now with an updated server version. Since I used an image that was provided for me I didn't look into the version being outdated. My bad. thanks for your fast reply! :)
