### ISSUE TITLE
New floating bug

### ISSUE THREAD

**Issue by SixtyTrees** [openvinotoolkit/cvat#3826]
CVAT is a great tool. We have used it for a year. Today it failed with an error for the first time. I have a set of 200 images labeled with 10 labels. I've tried to reshape a label, but got this.
TypeError
Cannot read property 'label' of undefined

TypeError: Cannot read property 'label' of undefined
    at Function.mapToProps (http://123.12.1.2:8080/cvat-ui.fa5ddfb98ff67cb8af82.min.js:80:866531)
    at a (http://123.12.1.2:8080/cvat-ui.fa5ddfb98ff67cb8af82.min.js:80:488220)
    at Function.a.mapToProps (http://123.12.1.2:8080/cvat-ui.fa5ddfb98ff67cb8af82.min.js:80:488356)
    at a (http://123.12.1.2:8080/cvat-ui.fa5ddfb98ff67cb8af82.min.js:80:488220)
    at http://123.12.1.2:8080/cvat-ui.fa5ddfb98ff67cb8af82.min.js:80:489575
    at http://123.12.1.2:8080/cvat-ui.fa5ddfb98ff67cb8af82.min.js:80:486599
    at Object.useMemo (http://123.12.1.2:8080/cvat-ui.fa5ddfb98ff67cb8af82.min.js:43:63498)
    at useMemo (http://123.12.1.2:8080/cvat-ui.fa5ddfb98ff67cb8af82.min.js:35:5228)
    at p (http://123.12.1.2:8080/cvat-ui.fa5ddfb98ff67cb8af82.min.js:80:486543)
    at ui (http://123.12.1.2:8080/cvat-ui.fa5ddfb98ff67cb8af82.min.js:43:59331)

The server is likely running on Windows, the client is running on windows + Opera browser.
This is the first error, so I don't know, how to reproduce it.

### My actions before raising this issue
- [V ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [V ] Searched [past issues](/issues)

### Current Behaviour

CVAT should allow me to reshape the fragment rather than fail with "Cannot read property 'label' of undefined"

### Possible Solution

No idea, this is a floating bug.

### Steps to Reproduce (for bugs)

This is the first time I see this error.

### Context

Mildly irritating, minor bug.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by nmanovic** [comment]
@SixtyTrees , unfortunately we don't support old versions. You need to upgrade your version. It is a good idea to backup your data.
