### ISSUE TITLE
Take exception "django.core.exceptions.ImproperlyConfigured: Cannot import 'dataset_repo'. Check that 'cvat.apps.dataset_repo.apps.GitConfig.name' is correct." on commands: python manage.py migrate

### ISSUE THREAD

**Issue by luori-mvp77** [openvinotoolkit/cvat#3838]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

I  clone the  develop branch to location, then completed my envs installation.  But take exception "django.core.exceptions.ImproperlyConfigured: Cannot import 'dataset_repo'. Check that 'cvat.apps.dataset_repo.apps.GitConfig.name' is correct." on commands: 
python manage.py migrate or python manage.py server.

How to fix? thanks

detail log:
$ python manage.py migrate
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/apps/config.py", line 244, in create
    app_module = import_module(app_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dataset_repo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/config.py", line 250, in create
    app_config_class.__qualname__,
django.core.exceptions.ImproperlyConfigured: Cannot import 'dataset_repo'. Check that 'cvat.apps.dataset_repo.apps.GitConfig.name' is correct.

### Your Environment

envs:
Ubuntu : 18.04
python: 3.6.9

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by luori-mvp77** [comment]
go on update to python3.9.6 take the same error. so i think maybe not  version  take  the error.

**Comment by luori-mvp77** [comment]
I fix the issue,  some files  to load module name miss  the prefix "cvat.apps.", like dataset_repo/apps.py, opencv/apps.py. then add the prefix  anything be ok.

**Comment by nmanovic** [comment]
@luori-mvp77 , you installed a newer version for Django. In develop the version of Django is 3.1.13. I will close the issue.

**Comment by nmanovic** [comment]
@luori-mvp77 , it is strange that you got the problem with the Django 3.1.x. You should get it only with Django 3.2.x

**Comment by luori-mvp77** [comment]
> @luori-mvp77 , it is strange that you got the problem with the Django 3.1.x. You should get it only with Django 3.2.x

Right. Make sure only  Django 3.1.x  version in.  I also take free time check to detail.

**Comment by nmanovic** [comment]
@luori-mvp77 , I will close the issue. Nobody complains about the issue. It looks like something wrong with your environment.
