### ISSUE TITLE
Django error while creating superuser

### ISSUE THREAD

**Issue by soax** [openvinotoolkit/cvat#3921]
Hi 

I try to install cvat docker image following the installation guide : 

https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/

After running 

`docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'`

I have the following error : 

```
/home/django/cvat/apps/training/jobs.py:78: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if TrainingProjectImage.objects.filter(task_id=task_id).count() is 0:
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'v1' isn't unique. You may not be able to reverse all URLs in this namespace
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/opt/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "cvat_db" to address: Temporary failure in name resolution

```
On Ubuntu 21.10

It's a fresh install I have just installed nividia-drivers an docker

Thanks for your help !

**Comment by azhavoro** [comment]
@soax 
Hi,
what is `docker ps output`?
Are you using any proxies on your network?

**Comment by soax** [comment]
Thanks for your answer.

Here is the output:

```
24323acdfaff   openvino/cvat_ui            "/docker-entrypoint.…"   4 hours ago         Up 4 hours                      80/tcp                                                                                         cvat_ui
037a758306cc   openvino/cvat_server        "/usr/bin/supervisord"   4 hours ago         Up 4 hours                      8080/tcp                                                                                       cvat
a4856b557f93   traefik:v2.4                "/entrypoint.sh --pr…"   4 hours ago         Up 4 hours                      0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 80/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   traefik
bc773396120e   redis:4.0-alpine            "docker-entrypoint.s…"   4 hours ago         Up 4 hours                      6379/tcp                                                                                       cvat_redis
4f0c48fb9a9f   postgres:10-alpine          "docker-entrypoint.s…"   4 hours ago         Restarting (1) 21 seconds ago                                                                                                  cvat_db
```
I don't think there is a proxy on the network.

I thought cvat runs locally ?

**Comment by azhavoro** [comment]
> 4f0c48fb9a9f   postgres:10-alpine          "docker-entrypoint.s…"   4 hours ago         Restarting (1) 21 seconds ago                                                                                                  cvat_db

For a reason cvat_db is not running, please attach logs from this container: `docker logs cvat_db > cvat_db.log`

> I thought cvat runs locally ?

Sure, I just asked some info that can help to solve the issue.

**Comment by soax** [comment]
Thanks,  it give me the solution ... not enough disk space.

```
initdb: could not create directory "/var/lib/postgresql/data/pg_wal": No space left on device
initdb: removing contents of data directory "/var/lib/postgresql/data"
```
It seems that microk8s has fill my disk ... I have to check that.

Thanks a lot for your time
