### ISSUE TITLE
Uploading Coco Annotation Error: status code 400. "can't import annotation #1 (polygon): annotation has no label"

### ISSUE THREAD

**Issue by frederick0291** [openvinotoolkit/cvat#3976]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

I am trying to upload a programmatically created json file in coco format to cvat but I keep getting an error that a polygon annotation has no label.
### Expected Behaviour

Uploading the coco annotation should work.

### Current Behaviour

Getting a status code 400 and I am not sure where the issue is.
### Steps to Reproduce (for bugs)

1. Create new task with the images.
1. Upload the json annotation file.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
[testUpload.zip](https://github.com/openvinotoolkit/cvat/files/7636253/testUpload.zip)
<summary> 
             raise CvatImportError("annotation has no label") 
         cvat.apps.dataset_manager.bindings.CvatImportError: annotation has no label
        During handling of the above exception, another exception occurred:
        Traceback (most recent call last):
          File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
            rv = job.perform()
          File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
            self._result = self._execute()
          File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
            return self.func(*self.args, **self.kwargs)
          File "/usr/lib/python3.8/contextlib.py", line 75, in inner
            return func(*args, **kwds)
          File "/home/django/cvat/apps/dataset_manager/task.py", line 758, in import_task_annotations
            task.import_annotations(f, importer)
          File "/home/django/cvat/apps/dataset_manager/task.py", line 641, in import_annotations
            importer(src_file, task_data, **options)
          File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 37, in __call__
            f_or_cls(*args, **kwargs)
          File "/home/django/cvat/apps/dataset_manager/formats/coco.py", line 34, in _import
            import_dm_annotations(dataset, instance_data)
          File "/home/django/cvat/apps/dataset_manager/bindings.py", line 1262, in import_dm_annotations
            raise CvatImportError("Image {}: can't import annotation "
        cvat.apps.dataset_manager.bindings.CvatImportError: Image 14084: can't import annotation #1 (polygon): annotation has no label
        Traceback (most recent call last):
          File "/home/django/cvat/apps/dataset_manager/bindings.py", line 1232, in import_dm_annotations
            raise CvatImportError("annotation has no label")
        cvat.apps.dataset_manager.bindings.CvatImportError: annotation has no label
        
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
          rv = job.perform()
        File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
          self._result = self._execute()
        File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
          return self.func(*self.args, **self.kwargs)
        File "/usr/lib/python3.8/contextlib.py", line 75, in inner
          return func(*args, **kwds)
        File "/home/django/cvat/apps/dataset_manager/task.py", line 758, in import_task_annotations
          task.import_annotations(f, importer)
        File "/home/django/cvat/apps/dataset_manager/task.py", line 641, in import_annotations
          importer(src_file, task_data, **options)
        File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 37, in __call__
          f_or_cls(*args, **kwargs)
        File "/home/django/cvat/apps/dataset_manager/formats/coco.py", line 34, in _import
          import_dm_annotations(dataset, instance_data)
        File "/home/django/cvat/apps/dataset_manager/bindings.py", line 1262, in import_dm_annotations
          raise CvatImportError("Image {}: can't import annotation "
      cvat.apps.dataset_manager.bindings.CvatImportError: Image 14084: can't import annotation #1 (polygon): annotation has no label
</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by frederick0291** [comment]
After checking the outputs, the issue was that inference was using a zero-indexed id for classes. Coco format is not zero-indexed. The script I made did not put this into consideration so all my classes were 1 off. There was a 0 class label in the output coco json hence the error where it was not able to find a label corresponding to 0.
