### ISSUE TITLE
error in docker-compose up -d

### ISSUE THREAD

**Issue by ioir123ju** [openvinotoolkit/cvat#4053]
ERROR: for cvat  dictionary update sequence element #0 has length 19; 2 is required
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 121, in perform_command
  File "compose/cli/main.py", line 952, in up
  File "compose/project.py", line 455, in up
  File "compose/parallel.py", line 70, in parallel_execute
ValueError: dictionary update sequence element #0 has length 19; 2 is required
Failed to execute script docker-compose

**Comment by bsekachev** [comment]
Hi, try to build one more time, try to reinstall docker-compose. 

@azhavoro  Do you have any ideas? I am not sure the issue is related with CVAT.

**Comment by azhavoro** [comment]
@ioir123ju what is version of docker-compose and python are you using?

**Comment by azhavoro** [comment]
There is no response for a long time, I will close the issue
