### ISSUE TITLE
AssertionError while downloading dataset in Yolo format

### ISSUE THREAD

**Issue by vikram-hacklab** [openvinotoolkit/cvat#4147]
### My actions before raising this issue
I was trying to download the dataset in Yolo format. 

I searched both existing issues and gitter for this error and couldn't find an exact reference. I saw a similar bug listed[ here 4122](https://github.com/openvinotoolkit/cvat/issues/4122) but it was only for a project but I am facing the issue when I try to download the data from a single task as well. 

### Expected Behaviour
Expected the zip of the dataset to be available for download

### Current Behaviour
Assert: Request failed with status code 500. "AssertionError: Smoke\n".

Error Log
DEBUG - 2022-01-11 14:52:52,426 - worker - Handling failed execution of job /api/v1/tasks/90/dataset/YOLO 1.1

2022-01-11 14:52:52,428 DEBG 'rqworker_default_1' stderr output:
ERROR - 2022-01-11 14:52:52,427 - worker - Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 100, in export_task_as_dataset
    return export(dst_format, task_id=task_id, server_url=server_url, save_images=True)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 75, in export
    export_fn(db_instance.id, temp_file, dst_format,
  File "/home/django/cvat/apps/dataset_manager/task.py", line 749, in export_task
    task.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 631, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 37, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/yolo.py", line 23, in _export
    dataset = Dataset.from_extractors(GetCVATDataExtractor(
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 1047, in GetCVATDataExtractor
    return CvatTaskDataExtractor(instance_data, include_images, format_type, dimension)
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 845, in __init__
    self._categories = self._load_categories(task_data.meta['task']['labels'])
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 813, in _load_categories
    label_categories.add(label['name'])
  File "/opt/venv/lib/python3.8/site-packages/datumaro/components/annotation.py", line 139, in add
    assert name not in self._indices, name
AssertionError: Smoke
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 936, in perform_job
    rv = job.perform()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 684, in perform
    self._result = self._execute()
  File "/opt/venv/lib/python3.8/site-packages/rq/job.py", line 690, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 100, in export_task_as_dataset
    return export(dst_format, task_id=task_id, server_url=server_url, save_images=True)
  File "/home/django/cvat/apps/dataset_manager/views.py", line 75, in export
    export_fn(db_instance.id, temp_file, dst_format,
  File "/home/django/cvat/apps/dataset_manager/task.py", line 749, in export_task
    task.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 631, in export
    exporter(dst_file, task_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 37, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/yolo.py", line 23, in _export
    dataset = Dataset.from_extractors(GetCVATDataExtractor(
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 1047, in GetCVATDataExtractor
    return CvatTaskDataExtractor(instance_data, include_images, format_type, dimension)
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 845, in __init__
    self._categories = self._load_categories(task_data.meta['task']['labels'])
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 813, in _load_categories
    label_categories.add(label['name'])
  File "/opt/venv/lib/python3.8/site-packages/datumaro/components/annotation.py", line 139, in add
    assert name not in self._indices, name
AssertionError: Smoke

### Environment
Cvat docker running on an AWS EC2 instance

**Comment by vikram-hacklab** [comment]
Issue resolved. Had two tags with same label 'Smoke'.
