### ISSUE TITLE
Could not reset password on the server. Open the Browser Console to get details.

### ISSUE THREAD

**Issue by Eslam-Elgebery** [openvinotoolkit/cvat#4342]
Dear Cvat.org and Github
One of my teammates had an issue regarding resetting her password as she got the error (Could not reset the password on the server. Open the Browser Console to get details.) while trying to reset her password.
She can't use her username instead of the e-mail also.
Please Assist and reply ASAP.
email:so3adahmed17@gmail.com
Thanks.

**Comment by azhavoro** [comment]
Thanks for the report!
Stacktrace
```python
[2022-02-14 12:11:05,177] ERROR django.request: Internal Server Error: /api/auth/password/reset
[Mon Feb 14 12:11:05.177927 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370] Traceback (most recent call last):
[Mon Feb 14 12:11:05.177930 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Mon Feb 14 12:11:05.177933 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     response = get_response(request)
[Mon Feb 14 12:11:05.177935 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Mon Feb 14 12:11:05.177938 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Mon Feb 14 12:11:05.177941 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Mon Feb 14 12:11:05.177943 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     return view_func(*args, **kwargs)
[Mon Feb 14 12:11:05.177945 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
[Mon Feb 14 12:11:05.177947 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     return self.dispatch(request, *args, **kwargs)
[Mon Feb 14 12:11:05.177949 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
[Mon Feb 14 12:11:05.177952 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     response = self.handle_exception(exc)
[Mon Feb 14 12:11:05.177953 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
[Mon Feb 14 12:11:05.177955 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     self.raise_uncaught_exception(exc)
[Mon Feb 14 12:11:05.177957 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Mon Feb 14 12:11:05.177960 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     raise exc
[Mon Feb 14 12:11:05.177961 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
[Mon Feb 14 12:11:05.177963 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     response = handler(request, *args, **kwargs)
[Mon Feb 14 12:11:05.177965 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/rest_auth/views.py", line 187, in post
[Mon Feb 14 12:11:05.177967 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     serializer.save()
[Mon Feb 14 12:11:05.177969 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/rest_auth/serializers.py", line 186, in save
[Mon Feb 14 12:11:05.177971 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     self.reset_form.save(**opts)
[Mon Feb 14 12:11:05.177973 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/contrib/auth/forms.py", line 310, in save
[Mon Feb 14 12:11:05.177975 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     self.send_mail(
[Mon Feb 14 12:11:05.177980 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/contrib/auth/forms.py", line 253, in send_mail

2022-02-14 12:11:05,178 DEBG 'runserver' stderr output:
[Mon Feb 14 12:11:05.177983 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     body = loader.render_to_string(email_template_name, context)
[Mon Feb 14 12:11:05.177987 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
[Mon Feb 14 12:11:05.177989 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     template = get_template(template_name, using=using)
[Mon Feb 14 12:11:05.177991 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
[Mon Feb 14 12:11:05.177993 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     raise TemplateDoesNotExist(template_name, chain=chain)
[Mon Feb 14 12:11:05.177995 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370] django.template.exceptions.TemplateDoesNotExist: auth/password_reset_email.html
[Mon Feb 14 12:11:05.178106 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370] ERROR - 2022-02-14 12:11:05,177 - log - Internal Server Error: /api/auth/password/reset
[Mon Feb 14 12:11:05.178109 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370] Traceback (most recent call last):
[Mon Feb 14 12:11:05.178111 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Mon Feb 14 12:11:05.178113 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     response = get_response(request)
[Mon Feb 14 12:11:05.178115 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Mon Feb 14 12:11:05.178117 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Mon Feb 14 12:11:05.178119 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Mon Feb 14 12:11:05.178122 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     return view_func(*args, **kwargs)
[Mon Feb 14 12:11:05.178124 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
[Mon Feb 14 12:11:05.178126 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     return self.dispatch(request, *args, **kwargs)
[Mon Feb 14 12:11:05.178128 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
[Mon Feb 14 12:11:05.178130 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     response = self.handle_exception(exc)
[Mon Feb 14 12:11:05.178132 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
[Mon Feb 14 12:11:05.178134 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     self.raise_uncaught_exception(exc)
[Mon Feb 14 12:11:05.178135 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
[Mon Feb 14 12:11:05.178138 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     raise exc
[Mon Feb 14 12:11:05.178139 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
[Mon Feb 14 12:11:05.178142 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     response = handler(request, *args, **kwargs)
[Mon Feb 14 12:11:05.178145 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/rest_auth/views.py", line 187, in post
[Mon Feb 14 12:11:05.178147 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     serializer.save()
[Mon Feb 14 12:11:05.178149 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/rest_auth/serializers.py", line 186, in save
[Mon Feb 14 12:11:05.178151 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     self.reset_form.save(**opts)
[Mon Feb 14 12:11:05.178153 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/contrib/auth/forms.py", line 310, in save
[Mon Feb 14 12:11:05.178155 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     self.send_mail(
[Mon Feb 14 12:11:05.178157 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/contrib/auth/forms.py", line 253, in send_mail
[Mon Feb 14 12:11:05.178159 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     body = loader.render_to_string(email_template_name, context)
[Mon Feb 14 12:11:05.178161 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
[Mon Feb 14 12:11:05.178163 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     template = get_template(template_name, using=using)
[Mon Feb 14 12:11:05.178165 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]   File "/opt/venv/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
[Mon Feb 14 12:11:05.178167 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370]     raise TemplateDoesNotExist(template_name, chain=chain)
[Mon Feb 14 12:11:05.178169 2022] [wsgi:error] [pid 434:tid 140198014211840] [remote 172.18.0.6:39370] django.template.exceptions.TemplateDoesNotExist: auth/password_reset_email.html
```

**Comment by azhavoro** [comment]
@Eslam-Elgebery Please wait some time for cvat.org to be updated.
