### ISSUE TITLE
Problems after CVAT update - failing login, then can't fetch project or tasks

### ISSUE THREAD

**Issue by qraleq** [openvinotoolkit/cvat#4356]
### My actions before raising this issue
- [ X ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ X ] Searched [past issues](/issues)

### Expected Behaviour

Being able to use CVAT after an update.

### Current Behaviour

I haven't updated CVAT server for a while, and I decided to do update it from this commit `b657113b99b1f4275d43706e3364b094a6305a09` to the latest `master`. I followed the instructions https://openvinotoolkit.github.io/cvat/docs/administration/advanced/backup_guide/ to backup and https://openvinotoolkit.github.io/cvat/docs/faq/#how-to-update-cvat to update the server.

After updating the CVAT server, I was having problems logging into CVAT. Then, I used `sudo docker exec -it cvat bash -ic 'python3 ~/manage.py migrate'` command, and now I can login into the server, but I'm having problems fetching Projects and Tasks. 

![image](https://user-images.githubusercontent.com/13619177/154496917-a9a8e5f3-ddd8-4422-b533-645e3597ef00.png)

This part of the `docker logs cvat` seems relevant:
```
2022-02-17 13:56:18,392 DEBG 'runserver' stderr output:
[Thu Feb 17 13:56:18.391577 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754] psycopg2.errors.UndefinedColumn: column engine_job.reviewer_id does not exist
[Thu Feb 17 13:56:18.391586 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754] LINE 1: ...ne_job"."segment_id", "engine_job"."assignee_id", "engine_jo...
[Thu Feb 17 13:56:18.391590 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]                                                              ^
[Thu Feb 17 13:56:18.391593 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754] 
[Thu Feb 17 13:56:18.391595 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754] 
[Thu Feb 17 13:56:18.391598 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754] The above exception was the direct cause of the following exception:
[Thu Feb 17 13:56:18.391601 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754] 
[Thu Feb 17 13:56:18.391603 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754] Traceback (most recent call last):
[Thu Feb 17 13:56:18.391606 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Thu Feb 17 13:56:18.391609 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     response = get_response(request)
[Thu Feb 17 13:56:18.391611 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Thu Feb 17 13:56:18.391616 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Feb 17 13:56:18.391620 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
[Thu Feb 17 13:56:18.391623 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     return view_func(*args, **kwargs)
[Thu Feb 17 13:56:18.391626 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
[Thu Feb 17 13:56:18.391628 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     return self.dispatch(request, *args, **kwargs)
[Thu Feb 17 13:56:18.391631 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
[Thu Feb 17 13:56:18.391635 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     response = self.handle_exception(exc)
[Thu Feb 17 13:56:18.391637 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
[Thu Feb 17 13:56:18.391641 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     self.raise_uncaught_exception(exc)
[Thu Feb 17 13:56:18.391643 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
[Thu Feb 17 13:56:18.391646 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     raise exc
[Thu Feb 17 13:56:18.391649 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
[Thu Feb 17 13:56:18.391652 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     response = handler(request, *args, **kwargs)
[Thu Feb 17 13:56:18.391655 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
[Thu Feb 17 13:56:18.391660 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     return bound_method(*args, **kwargs)
[Thu Feb 17 13:56:18.391663 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 40, in list
[Thu Feb 17 13:56:18.391665 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     page = self.paginate_queryset(queryset)
[Thu Feb 17 13:56:18.391668 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
[Thu Feb 17 13:56:18.391671 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     return self.paginator.paginate_queryset(queryset, self.request, view=self)
[Thu Feb 17 13:56:18.391674 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/pagination.py", line 218, in paginate_queryset
[Thu Feb 17 13:56:18.391677 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     return list(self.page)
[Thu Feb 17 13:56:18.391680 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/core/paginator.py", line 143, in __len__
[Thu Feb 17 13:56:18.391683 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     return len(self.object_list)
[Thu Feb 17 13:56:18.391685 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 269, in __len__
[Thu Feb 17 13:56:18.391688 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     self._fetch_all()
[Thu Feb 17 13:56:18.391691 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/cacheops/query.py", line 272, in _fetch_all
[Thu Feb 17 13:56:18.391693 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     return self._no_monkey._fetch_all(self)
[Thu Feb 17 13:56:18.391697 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1310, in _fetch_all
[Thu Feb 17 13:56:18.391699 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     self._prefetch_related_objects()
[Thu Feb 17 13:56:18.391702 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 814, in _prefetch_related_objects
[Thu Feb 17 13:56:18.391705 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
[Thu Feb 17 13:56:18.391708 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1710, in prefetch_related_objects
[Thu Feb 17 13:56:18.391711 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     obj_list, additional_lookups = prefetch_one_level(obj_list, prefetcher, lookup, level)
[Thu Feb 17 13:56:18.391713 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1823, in prefetch_one_level
[Thu Feb 17 13:56:18.391716 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     prefetcher.get_prefetch_queryset(instances, lookup.get_current_queryset(level)))
[Thu Feb 17 13:56:18.391719 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 636, in get_prefetch_queryset
[Thu Feb 17 13:56:18.391724 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     for rel_obj in queryset:
[Thu Feb 17 13:56:18.391726 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__
[Thu Feb 17 13:56:18.391729 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     self._fetch_all()
[Thu Feb 17 13:56:18.391731 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/cacheops/query.py", line 272, in _fetch_all
[Thu Feb 17 13:56:18.391734 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     return self._no_monkey._fetch_all(self)
[Thu Feb 17 13:56:18.391737 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
[Thu Feb 17 13:56:18.391740 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     self._result_cache = list(self._iterable_class(self))
[Thu Feb 17 13:56:18.391742 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
[Thu Feb 17 13:56:18.391745 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
[Thu Feb 17 13:56:18.391748 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
[Thu Feb 17 13:56:18.391751 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     cursor.execute(sql, params)
[Thu Feb 17 13:56:18.391754 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/cacheops/transaction.py", line 93, in execute
[Thu Feb 17 13:56:18.391757 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     result = self._no_monkey.execute(self, sql, params)
[Thu Feb 17 13:56:18.391759 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
[Thu Feb 17 13:56:18.391762 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
[Thu Feb 17 13:56:18.391765 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
[Thu Feb 17 13:56:18.391768 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     return executor(sql, params, many, context)
[Thu Feb 17 13:56:18.391770 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
[Thu Feb 17 13:56:18.391773 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     return self.cursor.execute(sql, params)
[Thu Feb 17 13:56:18.391776 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
[Thu Feb 17 13:56:18.391779 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     raise dj_exc_value.with_traceback(traceback) from exc_value
[Thu Feb 17 13:56:18.391781 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]   File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
[Thu Feb 17 13:56:18.391786 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]     return self.cursor.execute(sql, params)
[Thu Feb 17 13:56:18.391789 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754] django.db.utils.ProgrammingError: column engine_job.reviewer_id does not exist
[Thu Feb 17 13:56:18.391792 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754] LINE 1: ...ne_job"."segment_id", "engine_job"."assignee_id", "engine_jo...
[Thu Feb 17 13:56:18.391794 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754]                                                              ^
[Thu Feb 17 13:56:18.391797 2022] [wsgi:error] [pid 244:tid 139731279836928] [remote 172.18.0.2:55754] 
```

Can someone please help me restore the projects and tasks and other data from my server? 
Thank you!

**Comment by ZaibanAli** [comment]
Can you do a check on the size of the volume for CVAT using `docker system df`. If the size of the CVAT volume is big that means the data is still there. You can extract the information about the volumes using `docker system df -v`. After that please make a backup of these volumes and try to install the fresh CVAT and use these volumes.

**Comment by qraleq** [comment]
Hi @ZaibanAli, thank you for your reply. I don't see that CVAT volume is large using `docker system df -v`. But I have backup that I performed before the update. Can I just use that with fresh CVAT?

**Comment by qraleq** [comment]
Thank you very much @ZaibanAli , this did the trick!
