### ISSUE TITLE
n.map is not function

### ISSUE THREAD

**Issue by dotsinspace** [openvinotoolkit/cvat#4404]
### My actions before raising this issue
- [✓] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [✓] Searched [past issues](/issues)

### Expected Behaviour
No Error

### Current Behaviour
```
TypeError
n.map is not a function

TypeError: n.map is not a function
    at gc (http://3.111.188.218/cvat-ui.580642541947bec0314e.min.js:372:508469)
    at Ko (http://3.111.188.218/cvat-ui.580642541947bec0314e.min.js:346:57930)
    at Ri (http://3.111.188.218/cvat-ui.580642541947bec0314e.min.js:346:66791)
    at Di (http://3.111.188.218/cvat-ui.580642541947bec0314e.min.js:346:66610)
    at Ai (http://3.111.188.218/cvat-ui.580642541947bec0314e.min.js:346:66293)
    at vs (http://3.111.188.218/cvat-ui.580642541947bec0314e.min.js:346:107698)
    at cl (http://3.111.188.218/cvat-ui.580642541947bec0314e.min.js:346:96717)
    at sl (http://3.111.188.218/cvat-ui.580642541947bec0314e.min.js:346:96642)
    at Qs (http://3.111.188.218/cvat-ui.580642541947bec0314e.min.js:346:93672)
    at http://3.111.188.218/cvat-ui.580642541947bec0314e.min.js:346:45314
```

### Steps to Reproduce (for bugs)
1. git clone https://github.com/opencv/cvat
2. cd cvat
3. docker-compose up -d
4. docker exec -it cvat bash -ic 'python3 ~/manage.py createsuperuser'

### Context
Unable to login or Register

### Your Environment

- commit 6fad1764efd922d99dbcda28c4ee72d071aa5a07
- Docker version 20.10.12, build e91ed57
- No Docker Swarm or Kubernetes
- Linux Os

**Comment by bsekachev** [comment]
Hi @dotsinspace 

In order to we could help you, will you please provide:

- Screenshots from the browser console?
- From the browser Network tab?
- CVAT version?

**Comment by dotsinspace** [comment]
**1.Screenshot**
![image](https://user-images.githubusercontent.com/76559517/156196701-84d5c430-2c86-4aba-91cc-37ccfec05ff0.png)

**2. Network Tab**
![image](https://user-images.githubusercontent.com/76559517/156196947-dd4d49e0-825c-4b3a-9717-559a9079d315.png)

3.Latest ( Just Spined Docker Today. Expecting it to be 1.7.0)

**Comment by bsekachev** [comment]
@dotsinspace 

Please, update page after opening network tab. As you can see it is empty on your screenshot. 
Also you can look at #4388, there was similar issue and root cause was incorrect compose configuration.
