### ISSUE TITLE
Internal server error because Redis RDB snapshotting failure

### ISSUE THREAD

**Issue by timurlenk07** [openvinotoolkit/cvat#4539]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

After weeks of successful operation, the CVAT app suddenly started to emit internal server errors, with `redis.exception.ResponseError`s present in **all of the error log files**.

The CVAT app on our company server is up and running for the last 11 days, and since about a week before, we have started to use it more intensively with 10k of images in just a couple of tasks (not sure if this is relevant). It was working as expected, but about 14 hours ago something changed and now nothing is working as the server constantly emits internal server error responses.
In the last week, we did not change anything that is related to the CVAT servers or their db/log/keys volumes, though we have mounted folders for all the volume components available in the CVAT docker-compose file.

### Current Behaviour

The tasks page won't load properly, the task details page won't load properly, if I want to open a job I get *Sorry, but this job was not found*.
Logging in and out seems to work properly, and also the admin page works without errors.

### Steps to Reproduce (for bugs)

No idea how to reproduce (run CVAT for 2 weeks maybe?)

### Context

Pretty much nothing changed between normal operation and the point where redis started throwing exceptions. We were creating projects and labels configs, tasks and uploaded annotations (in CVAT format), all via the UI options of the application.

### Your Environment

- Git hash commit (`git log -1`): tag v2.0.0
- Docker version `docker version` (e.g. Docker 17.0.05): Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2
- Are you using Docker Swarm or Kubernetes? docker-compose
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04.3 LTS
- Using the app via VPN and port accessible only on local network
- Other diagnostic information / logs:
    Logs from `cvat` container: The full log is too long to be fully included here. The log if I simply open the app which I am already logged into and shows up this tasks page:
![image](https://user-images.githubusercontent.com/25661746/161375250-e4e35165-e75c-422d-a872-8189f898589d.png)
 (log of the last minute): [container_cvat.log](https://github.com/openvinotoolkit/cvat/files/8402152/container_cvat.log)

The error that keeps repeating itself all over the logs is the following:
```
2022-04-02 08:43:01,032 DEBG 'rqworker_low' stderr output:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/redis/client.py", line 3911, in _execute_transaction
    response = self.parse_response(connection, '_')
  File "/opt/venv/lib/python3.8/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "/opt/venv/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/opt/venv/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/django/manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/venv/lib/python3.8/site-packages/django_rq/management/commands/rqworker.py", line 102, in handle
    w.work(burst=options.get('burst', False), with_scheduler=options.get('with_scheduler', False), logging_level=level)
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 508, in work
    self.register_birth()
  File "/opt/venv/lib/python3.8/site-packages/rq/worker.py", line 299, in register_birth
    p.execute()
  File "/opt/venv/lib/python3.8/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "/opt/venv/lib/python3.8/site-packages/redis/client.py", line 3914, in _execute_transaction
    raise errors[0][1]
  File "/opt/venv/lib/python3.8/site-packages/redis/client.py", line 3904, in _execute_transaction
    self.parse_response(connection, '_')
  File "/opt/venv/lib/python3.8/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "/opt/venv/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/opt/venv/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (DEL rq:worker:d5fc47f3d1134b52847dd8cca7af7031) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```

*docker_compose.yml* modifications (volumes mounted):
```
volumes:
  cvat_db:
    driver_opts:
      type: none
      device: /path/to/project/root/db
      o: bind
  cvat_data:
    driver_opts:
      type: none
      device: /path/to/project/root/data
      o: bind
  cvat_keys:
    driver_opts:
      type: none
      device: /path/to/project/root/keys
      o: bind
  cvat_logs:
    driver_opts:
      type: none
      device: /path/to/project/root/logs
      o: bind
  cvat_share:
    driver_opts:
      type: none
      device: /path/to/our/data
      o: bind
```

**Comment by timurlenk07** [comment]
Well, it seems the problem was that the `/tmp` dir was full and after freeing up some space, things seem to work correctly. Good thing I did not spent an houron writing the issue... 😆
