### ISSUE TITLE
Cannot login 

### ISSUE THREAD

**Issue by claudio9russo7** [openvinotoolkit/cvat#4611]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I tried to login from googlechrome in cvat.org

### Steps to Reproduce (for bugs)

1.Open googlechrome
1.Cvat.org

### Context
 Try to login the browser version of cvat

### Your Environment

-Windows
Googlechrome
Cannot read properties of null (reading 'dumpers')
TypeError: Cannot read properties of null (reading 'dumpers')
    at https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:372:728328
    at https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:372:338531
    at https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:372:339065
    at Sv (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:372:728294)
    at Ko (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:57930)
    at Ri (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:66791)
    at Di (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:66610)
    at Ai (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:66293)
    at gs (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:107698)
    at cl (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:96717)
    

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by claudio9russo7** [comment]
This is what i see:
![cvat_error](https://user-images.githubusercontent.com/99536010/166304528-0e44e774-6111-4410-8412-79bb4aadabc9.png)
