### ISSUE TITLE
KeyError: 'result' after login 

### ISSUE THREAD

**Issue by ManuelEberhardinger** [openvinotoolkit/cvat#4656]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

Login should work.

### Current Behaviour

I first did a deployment on my local Macbook without any problems. After that I wanted to deploy that on a Debian server and I got this error after creating a super user and logging in:
````cvat          | [Tue May 24 14:45:56.507584 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086] ERROR - 2022-05-24 14:45:56,506 - log - Internal Server Error: /api/users/self
cvat          | [Tue May 24 14:45:56.507590 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086] Traceback (most recent call last):
cvat          | [Tue May 24 14:45:56.507594 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
cvat          | [Tue May 24 14:45:56.507598 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]     response = get_response(request)
cvat          | [Tue May 24 14:45:56.507602 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]   File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
cvat          | [Tue May 24 14:45:56.507606 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
cvat          | [Tue May 24 14:45:56.507610 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]   File "/opt/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
cvat          | [Tue May 24 14:45:56.507613 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]     return view_func(*args, **kwargs)
cvat          | [Tue May 24 14:45:56.507617 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
cvat          | [Tue May 24 14:45:56.507621 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]     return self.dispatch(request, *args, **kwargs)
cvat          | [Tue May 24 14:45:56.507625 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
cvat          | [Tue May 24 14:45:56.507628 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]     response = self.handle_exception(exc)
cvat          | [Tue May 24 14:45:56.507632 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
cvat          | [Tue May 24 14:45:56.507636 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]     self.raise_uncaught_exception(exc)
cvat          | [Tue May 24 14:45:56.507640 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
cvat          | [Tue May 24 14:45:56.507644 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]     raise exc
cvat          | [Tue May 24 14:45:56.507647 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 497, in dispatch
cvat          | [Tue May 24 14:45:56.507651 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]     self.initial(request, *args, **kwargs)
cvat          | [Tue May 24 14:45:56.507655 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 415, in initial
cvat          | [Tue May 24 14:45:56.507659 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]     self.check_permissions(request)
cvat          | [Tue May 24 14:45:56.507662 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]   File "/opt/venv/lib/python3.8/site-packages/rest_framework/views.py", line 332, in check_permissions
cvat          | [Tue May 24 14:45:56.507666 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]     if not permission.has_permission(request, self):
cvat          | [Tue May 24 14:45:56.507670 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]   File "/home/django/cvat/apps/iam/permissions.py", line 1041, in has_permission
cvat          | [Tue May 24 14:45:56.507674 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]     return self.check_permission(request, view, None)
cvat          | [Tue May 24 14:45:56.507678 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]   File "/home/django/cvat/apps/iam/permissions.py", line 1037, in check_permission
cvat          | [Tue May 24 14:45:56.507682 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]     return all(permissions)
cvat          | [Tue May 24 14:45:56.507686 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]   File "/home/django/cvat/apps/iam/permissions.py", line 79, in __bool__
cvat          | [Tue May 24 14:45:56.507690 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086]     return r.json()['result']
cvat          | [Tue May 24 14:45:56.507694 2022] [wsgi:error] [pid 593:tid 139974827357952] [remote 10.81.47.7:54086] KeyError: 'result'
````

### Possible Solution
I don't know if the actual problem is on your site or in the opa container as somehow the result key is missing in the response. When I check the log output of the opa service on my Macbook the output is: 
````
cvat_opa      | {"client_addr":"192.168.112.6:47686","level":"info","msg":"Received request.","req_id":41,"req_method":"POST","req_path":"/v1/data/users/allow","time":"2022-05-24T14:30:52Z"}
cvat_opa      | {"decision_id":"35d73b44-256f-4726-b7b2-4918dd331dc2","input":{"auth":{"organization":null,"user":{"id":1,"privilege":"admin"}},"resource":{"id":1,"membership":{"role":null}},"scope":"view"},"labels":{"id":"022e117b-542f-4a22-97c3-98a189d3dd06","version":"0.34.2"},"level":"info","metrics":{"counter_server_query_cache_hit":1,"timer_rego_input_parse_ns":1517800,"timer_rego_query_eval_ns":3751500,"timer_server_handler_ns":5991800},"msg":"Decision Log","path":"users/allow","requested_by":"192.168.112.6:47686","result":true,"time":"2022-05-24T14:30:52Z","timestamp":"2022-05-24T14:30:52.0731411Z","type":"openpolicyagent.org/decision_logs"}
cvat_opa      | {"client_addr":"192.168.112.6:47686","level":"info","msg":"Sent response.","req_id":41,"req_method":"POST","req_path":"/v1/data/users/allow","resp_bytes":68,"resp_duration":20.2437,"resp_status":200,"time":"2022-05-24T14:30:52Z"}
````
On the Debian server the only difference is that the `"resp_bytes":54` (the ns values are also different).

### Steps to Reproduce (for bugs)
Deploy the stack with docker-compose on Debian.

`````
git clone https://github.com/openvinotoolkit/cvat.git
docker-compose up -d
`````
### Your Environment

- Git hash commit (`git log -1`): commit d7560bbd39fec68f944515c2591dda74f3764b90
- Docker version `docker version` (e.g. Docker 17.0.05): Client:  20.10.2 Server: 19.03.12
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Debian 10 Buster
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by KoheiKanagu** [comment]
@ManuelEberhardinger 
I had the same problem, but it was caused by the rules directory not being mounted correctly.

https://github.com/openvinotoolkit/cvat/blob/d7560bbd39fec68f944515c2591dda74f3764b90/docker-compose.yml#L103-L104

**Comment by nmanovic** [comment]
@ManuelEberhardinger , please check that OPA is up and running.

**Comment by ManuelEberhardinger** [comment]
> @ManuelEberhardinger I had the same problem, but it was caused by the rules directory not being mounted correctly.
> 
> https://github.com/openvinotoolkit/cvat/blob/d7560bbd39fec68f944515c2591dda74f3764b90/docker-compose.yml#L103-L104

Thanks a lot that was the problem! I was looking for hours for the problem yesterday, but couldn't think about that the folder was not mounted properly 😄
