### ISSUE TITLE
Could not login CVAT.org

### ISSUE THREAD

**Issue by nht-1999** [openvinotoolkit/cvat#4685]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)
When I'm trying to label data on CVAT.org, this page suddenly returns the login page.
After that, I have this error when logging in to my account. Can everyone help me fix it? I had this error yesterday but this morning it disappeared.
TypeError
Cannot read properties of null (reading 'dumpers')

TypeError: Cannot read properties of null (reading 'dumpers')
    at https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:372:728328
    at https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:372:338531
    at https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:372:339065
    at Sv (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:372:728294)
    at Ko (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:57930)
    at Ri (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:66791)
    at Di (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:66610)
    at Ai (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:66293)
    at gs (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:107698)
    at cl (https://cvat.org/assets/cvat-ui.d910472c6024744d9671.min.js:346:96717)

![image](https://user-images.githubusercontent.com/56917422/173030615-a499bc98-d6a2-4d17-940d-324f3ceeac10.png)

**Comment by Hiszarul** [comment]
I have the same problem. How to fix this?

**Comment by MosesNjau** [comment]
I have same issue also

**Comment by nht-1999** [comment]
> Please send your questions about CVAT.org to https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/bd-p/distribution-openvino-toolkit forum. I hope they will help and answer.

Thanks for all. I think I will use it within a limited time.

**Comment by yustiks** [comment]
same for me. It doesn't work
